// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: msg.service.proto

package rpc_client

import (
	context "context"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	types "github.com/gogo/protobuf/types"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
	mtproto "novachat_engine/mtproto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("msg.service.proto", fileDescriptor_2a57001837ecee2b) }

var fileDescriptor_2a57001837ecee2b = []byte{
	// 255 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x41, 0x4b, 0x03, 0x31,
	0x10, 0x85, 0x8b, 0x07, 0x0f, 0x41, 0x74, 0x1b, 0x0a, 0xda, 0x1c, 0xfb, 0x03, 0xa6, 0xa0, 0x67,
	0x91, 0x0a, 0x45, 0x2f, 0x05, 0x49, 0xf1, 0xe2, 0x45, 0xd2, 0xec, 0x18, 0x83, 0xbb, 0xc9, 0xee,
	0x4e, 0x2c, 0xec, 0xaf, 0xf5, 0xaf, 0x88, 0x49, 0xab, 0x59, 0x70, 0x8f, 0x99, 0x6f, 0xde, 0x9b,
	0xf7, 0x08, 0x9b, 0xd6, 0x64, 0x80, 0xb0, 0xdb, 0x5b, 0x8d, 0xd0, 0x74, 0x3e, 0x78, 0xce, 0xba,
	0x46, 0xbf, 0xea, 0xca, 0xa2, 0x0b, 0x62, 0x46, 0xfa, 0x1d, 0x6b, 0x05, 0xa1, 0x02, 0xea, 0x9d,
	0x4e, 0x1b, 0xa2, 0x38, 0x4c, 0x7f, 0xb4, 0x69, 0x32, 0x37, 0xde, 0x9b, 0x0a, 0x97, 0xf1, 0xb5,
	0xfb, 0x7c, 0x5b, 0x2a, 0xd7, 0x27, 0x74, 0xfd, 0x75, 0xc2, 0xd8, 0x86, 0xcc, 0x36, 0xdd, 0xe0,
	0x77, 0xec, 0x42, 0x62, 0xbb, 0x45, 0x57, 0x6e, 0x90, 0x48, 0x19, 0x24, 0x7e, 0x05, 0x7f, 0x17,
	0x21, 0x27, 0xa2, 0x80, 0x3a, 0x44, 0x17, 0x78, 0x6e, 0x4a, 0x15, 0x90, 0x16, 0x13, 0x7e, 0xcb,
	0xce, 0x25, 0xb6, 0xeb, 0xd2, 0x86, 0xc3, 0x1a, 0xbf, 0xcc, 0xf5, 0x19, 0xf8, 0x57, 0xfe, 0xc0,
	0xa6, 0x12, 0x5b, 0x89, 0x7b, 0xff, 0x81, 0xbf, 0x09, 0x44, 0xee, 0x30, 0x64, 0x62, 0x06, 0xa9,
	0x1b, 0x1c, 0xbb, 0xc1, 0xca, 0xf5, 0x8b, 0x09, 0x5f, 0xc5, 0x1c, 0x12, 0x55, 0xf9, 0x68, 0x29,
	0xf8, 0xae, 0x1f, 0xe6, 0xc8, 0xc0, 0xa8, 0xc5, 0x9a, 0x15, 0x12, 0xdb, 0x27, 0xeb, 0x1c, 0x1e,
	0x3b, 0xf3, 0x79, 0x6e, 0x32, 0x40, 0x63, 0x36, 0xf7, 0x67, 0x2f, 0xd9, 0x97, 0xed, 0x4e, 0x23,
	0xbd, 0xf9, 0x0e, 0x00, 0x00, 0xff, 0xff, 0xf8, 0x5d, 0x93, 0x48, 0xda, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgServiceClient is the client API for MsgService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgServiceClient interface {
	ReqSendMessages(ctx context.Context, in *SendMessages, opts ...grpc.CallOption) (*mtproto.Updates, error)
	ReqEditMessage(ctx context.Context, in *EditMessage, opts ...grpc.CallOption) (*mtproto.Updates, error)
	ReqRevokeMessages(ctx context.Context, in *RevokeMessages, opts ...grpc.CallOption) (*types.Any, error)
	ReqReadHistory(ctx context.Context, in *ReadHistory, opts ...grpc.CallOption) (*types.Any, error)
	ReqPinnedMessage(ctx context.Context, in *PinnedMessage, opts ...grpc.CallOption) (*types.Any, error)
}

type msgServiceClient struct {
	cc *grpc.ClientConn
}

func NewMsgServiceClient(cc *grpc.ClientConn) MsgServiceClient {
	return &msgServiceClient{cc}
}

func (c *msgServiceClient) ReqSendMessages(ctx context.Context, in *SendMessages, opts ...grpc.CallOption) (*mtproto.Updates, error) {
	out := new(mtproto.Updates)
	err := c.cc.Invoke(ctx, "/rpc_client.MsgService/ReqSendMessages", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgServiceClient) ReqEditMessage(ctx context.Context, in *EditMessage, opts ...grpc.CallOption) (*mtproto.Updates, error) {
	out := new(mtproto.Updates)
	err := c.cc.Invoke(ctx, "/rpc_client.MsgService/ReqEditMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgServiceClient) ReqRevokeMessages(ctx context.Context, in *RevokeMessages, opts ...grpc.CallOption) (*types.Any, error) {
	out := new(types.Any)
	err := c.cc.Invoke(ctx, "/rpc_client.MsgService/ReqRevokeMessages", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgServiceClient) ReqReadHistory(ctx context.Context, in *ReadHistory, opts ...grpc.CallOption) (*types.Any, error) {
	out := new(types.Any)
	err := c.cc.Invoke(ctx, "/rpc_client.MsgService/ReqReadHistory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgServiceClient) ReqPinnedMessage(ctx context.Context, in *PinnedMessage, opts ...grpc.CallOption) (*types.Any, error) {
	out := new(types.Any)
	err := c.cc.Invoke(ctx, "/rpc_client.MsgService/ReqPinnedMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServiceServer is the server API for MsgService service.
type MsgServiceServer interface {
	ReqSendMessages(context.Context, *SendMessages) (*mtproto.Updates, error)
	ReqEditMessage(context.Context, *EditMessage) (*mtproto.Updates, error)
	ReqRevokeMessages(context.Context, *RevokeMessages) (*types.Any, error)
	ReqReadHistory(context.Context, *ReadHistory) (*types.Any, error)
	ReqPinnedMessage(context.Context, *PinnedMessage) (*types.Any, error)
}

// UnimplementedMsgServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServiceServer struct {
}

func (*UnimplementedMsgServiceServer) ReqSendMessages(ctx context.Context, req *SendMessages) (*mtproto.Updates, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReqSendMessages not implemented")
}
func (*UnimplementedMsgServiceServer) ReqEditMessage(ctx context.Context, req *EditMessage) (*mtproto.Updates, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReqEditMessage not implemented")
}
func (*UnimplementedMsgServiceServer) ReqRevokeMessages(ctx context.Context, req *RevokeMessages) (*types.Any, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReqRevokeMessages not implemented")
}
func (*UnimplementedMsgServiceServer) ReqReadHistory(ctx context.Context, req *ReadHistory) (*types.Any, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReqReadHistory not implemented")
}
func (*UnimplementedMsgServiceServer) ReqPinnedMessage(ctx context.Context, req *PinnedMessage) (*types.Any, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReqPinnedMessage not implemented")
}

func RegisterMsgServiceServer(s *grpc.Server, srv MsgServiceServer) {
	s.RegisterService(&_MsgService_serviceDesc, srv)
}

func _MsgService_ReqSendMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessages)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServiceServer).ReqSendMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc_client.MsgService/ReqSendMessages",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServiceServer).ReqSendMessages(ctx, req.(*SendMessages))
	}
	return interceptor(ctx, in, info, handler)
}

func _MsgService_ReqEditMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServiceServer).ReqEditMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc_client.MsgService/ReqEditMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServiceServer).ReqEditMessage(ctx, req.(*EditMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _MsgService_ReqRevokeMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeMessages)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServiceServer).ReqRevokeMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc_client.MsgService/ReqRevokeMessages",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServiceServer).ReqRevokeMessages(ctx, req.(*RevokeMessages))
	}
	return interceptor(ctx, in, info, handler)
}

func _MsgService_ReqReadHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadHistory)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServiceServer).ReqReadHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc_client.MsgService/ReqReadHistory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServiceServer).ReqReadHistory(ctx, req.(*ReadHistory))
	}
	return interceptor(ctx, in, info, handler)
}

func _MsgService_ReqPinnedMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PinnedMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServiceServer).ReqPinnedMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc_client.MsgService/ReqPinnedMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServiceServer).ReqPinnedMessage(ctx, req.(*PinnedMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _MsgService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc_client.MsgService",
	HandlerType: (*MsgServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReqSendMessages",
			Handler:    _MsgService_ReqSendMessages_Handler,
		},
		{
			MethodName: "ReqEditMessage",
			Handler:    _MsgService_ReqEditMessage_Handler,
		},
		{
			MethodName: "ReqRevokeMessages",
			Handler:    _MsgService_ReqRevokeMessages_Handler,
		},
		{
			MethodName: "ReqReadHistory",
			Handler:    _MsgService_ReqReadHistory_Handler,
		},
		{
			MethodName: "ReqPinnedMessage",
			Handler:    _MsgService_ReqPinnedMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "msg.service.proto",
}

var MsgService_serviceDesc = map[string][]interface{}{
	"SendMessages": {
		"/rpc_client.MsgService/ReqSendMessages",
		func() interface{} { return new(mtproto.Updates) },
		"ReqSendMessages",
	},
	"EditMessage": {
		"/rpc_client.MsgService/ReqEditMessage",
		func() interface{} { return new(mtproto.Updates) },
		"ReqEditMessage",
	},
	"RevokeMessages": {
		"/rpc_client.MsgService/ReqRevokeMessages",
		func() interface{} { return new(types.Any) },
		"ReqRevokeMessages",
	},
	"ReadHistory": {
		"/rpc_client.MsgService/ReqReadHistory",
		func() interface{} { return new(types.Any) },
		"ReqReadHistory",
	},
	"PinnedMessage": {
		"/rpc_client.MsgService/ReqPinnedMessage",
		func() interface{} { return new(types.Any) },
		"ReqPinnedMessage",
	},
}
