// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: schema.service.type.proto

package mtproto

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// account.getWallPapers
type Response_AccountGetWallPapers struct {
	Cmd                          uint32              `protobuf:"varint,1,opt,name=cmd,proto3" json:"cmd,omitempty"`
	AccountGetWallPapersc04Cfac2 *Vector_WallPaper   `protobuf:"bytes,2,opt,name=AccountGetWallPapersc04Cfac2,proto3" json:"AccountGetWallPapersc04Cfac2,omitempty"`
	AccountGetWallPapersaabb1763 *Account_WallPapers `protobuf:"bytes,3,opt,name=AccountGetWallPapersaabb1763,proto3" json:"AccountGetWallPapersaabb1763,omitempty"`
	XXX_NoUnkeyedLiteral         struct{}            `json:"-"`
	XXX_unrecognized             []byte              `json:"-"`
	XXX_sizecache                int32               `json:"-"`
}

func (m *Response_AccountGetWallPapers) Reset()         { *m = Response_AccountGetWallPapers{} }
func (m *Response_AccountGetWallPapers) String() string { return proto.CompactTextString(m) }
func (*Response_AccountGetWallPapers) ProtoMessage()    {}
func (*Response_AccountGetWallPapers) Descriptor() ([]byte, []int) {
	return fileDescriptor_87f3599dbacd6972, []int{0}
}
func (m *Response_AccountGetWallPapers) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Response_AccountGetWallPapers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Response_AccountGetWallPapers.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Response_AccountGetWallPapers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response_AccountGetWallPapers.Merge(m, src)
}
func (m *Response_AccountGetWallPapers) XXX_Size() int {
	return m.Size()
}
func (m *Response_AccountGetWallPapers) XXX_DiscardUnknown() {
	xxx_messageInfo_Response_AccountGetWallPapers.DiscardUnknown(m)
}

var xxx_messageInfo_Response_AccountGetWallPapers proto.InternalMessageInfo

func (m *Response_AccountGetWallPapers) GetCmd() uint32 {
	if m != nil {
		return m.Cmd
	}
	return 0
}

func (m *Response_AccountGetWallPapers) GetAccountGetWallPapersc04Cfac2() *Vector_WallPaper {
	if m != nil {
		return m.AccountGetWallPapersc04Cfac2
	}
	return nil
}

func (m *Response_AccountGetWallPapers) GetAccountGetWallPapersaabb1763() *Account_WallPapers {
	if m != nil {
		return m.AccountGetWallPapersaabb1763
	}
	return nil
}

// contacts.deleteContacts
type Response_ContactsDeleteContacts struct {
	Cmd                            uint32   `protobuf:"varint,1,opt,name=cmd,proto3" json:"cmd,omitempty"`
	ContactsDeleteContacts59Ab389E *Bool    `protobuf:"bytes,2,opt,name=ContactsDeleteContacts59Ab389E,proto3" json:"ContactsDeleteContacts59Ab389E,omitempty"`
	ContactsDeleteContacts96A0E00  *Updates `protobuf:"bytes,3,opt,name=ContactsDeleteContacts96A0E00,proto3" json:"ContactsDeleteContacts96A0E00,omitempty"`
	XXX_NoUnkeyedLiteral           struct{} `json:"-"`
	XXX_unrecognized               []byte   `json:"-"`
	XXX_sizecache                  int32    `json:"-"`
}

func (m *Response_ContactsDeleteContacts) Reset()         { *m = Response_ContactsDeleteContacts{} }
func (m *Response_ContactsDeleteContacts) String() string { return proto.CompactTextString(m) }
func (*Response_ContactsDeleteContacts) ProtoMessage()    {}
func (*Response_ContactsDeleteContacts) Descriptor() ([]byte, []int) {
	return fileDescriptor_87f3599dbacd6972, []int{1}
}
func (m *Response_ContactsDeleteContacts) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Response_ContactsDeleteContacts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Response_ContactsDeleteContacts.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Response_ContactsDeleteContacts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response_ContactsDeleteContacts.Merge(m, src)
}
func (m *Response_ContactsDeleteContacts) XXX_Size() int {
	return m.Size()
}
func (m *Response_ContactsDeleteContacts) XXX_DiscardUnknown() {
	xxx_messageInfo_Response_ContactsDeleteContacts.DiscardUnknown(m)
}

var xxx_messageInfo_Response_ContactsDeleteContacts proto.InternalMessageInfo

func (m *Response_ContactsDeleteContacts) GetCmd() uint32 {
	if m != nil {
		return m.Cmd
	}
	return 0
}

func (m *Response_ContactsDeleteContacts) GetContactsDeleteContacts59Ab389E() *Bool {
	if m != nil {
		return m.ContactsDeleteContacts59Ab389E
	}
	return nil
}

func (m *Response_ContactsDeleteContacts) GetContactsDeleteContacts96A0E00() *Updates {
	if m != nil {
		return m.ContactsDeleteContacts96A0E00
	}
	return nil
}

// help.getAppChangelog
type Response_HelpGetAppChangelog struct {
	Cmd                         uint32             `protobuf:"varint,1,opt,name=cmd,proto3" json:"cmd,omitempty"`
	HelpGetAppChangelog9010Ef6F *Updates           `protobuf:"bytes,2,opt,name=HelpGetAppChangelog9010Ef6F,proto3" json:"HelpGetAppChangelog9010Ef6F,omitempty"`
	HelpGetAppChangelog5Bab7Fb2 *Help_AppChangelog `protobuf:"bytes,3,opt,name=HelpGetAppChangelog5Bab7Fb2,proto3" json:"HelpGetAppChangelog5Bab7Fb2,omitempty"`
	XXX_NoUnkeyedLiteral        struct{}           `json:"-"`
	XXX_unrecognized            []byte             `json:"-"`
	XXX_sizecache               int32              `json:"-"`
}

func (m *Response_HelpGetAppChangelog) Reset()         { *m = Response_HelpGetAppChangelog{} }
func (m *Response_HelpGetAppChangelog) String() string { return proto.CompactTextString(m) }
func (*Response_HelpGetAppChangelog) ProtoMessage()    {}
func (*Response_HelpGetAppChangelog) Descriptor() ([]byte, []int) {
	return fileDescriptor_87f3599dbacd6972, []int{2}
}
func (m *Response_HelpGetAppChangelog) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Response_HelpGetAppChangelog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Response_HelpGetAppChangelog.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Response_HelpGetAppChangelog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response_HelpGetAppChangelog.Merge(m, src)
}
func (m *Response_HelpGetAppChangelog) XXX_Size() int {
	return m.Size()
}
func (m *Response_HelpGetAppChangelog) XXX_DiscardUnknown() {
	xxx_messageInfo_Response_HelpGetAppChangelog.DiscardUnknown(m)
}

var xxx_messageInfo_Response_HelpGetAppChangelog proto.InternalMessageInfo

func (m *Response_HelpGetAppChangelog) GetCmd() uint32 {
	if m != nil {
		return m.Cmd
	}
	return 0
}

func (m *Response_HelpGetAppChangelog) GetHelpGetAppChangelog9010Ef6F() *Updates {
	if m != nil {
		return m.HelpGetAppChangelog9010Ef6F
	}
	return nil
}

func (m *Response_HelpGetAppChangelog) GetHelpGetAppChangelog5Bab7Fb2() *Help_AppChangelog {
	if m != nil {
		return m.HelpGetAppChangelog5Bab7Fb2
	}
	return nil
}

// messages.getMessagesViews
type Response_MessagesGetMessagesViews struct {
	Cmd                              uint32                 `protobuf:"varint,1,opt,name=cmd,proto3" json:"cmd,omitempty"`
	MessagesGetMessagesViewsc4C8A55D *VectorInt             `protobuf:"bytes,2,opt,name=MessagesGetMessagesViewsc4C8A55D,proto3" json:"MessagesGetMessagesViewsc4C8A55D,omitempty"`
	MessagesGetMessagesViews5784D3E1 *Messages_MessageViews `protobuf:"bytes,3,opt,name=MessagesGetMessagesViews5784D3E1,proto3" json:"MessagesGetMessagesViews5784D3E1,omitempty"`
	XXX_NoUnkeyedLiteral             struct{}               `json:"-"`
	XXX_unrecognized                 []byte                 `json:"-"`
	XXX_sizecache                    int32                  `json:"-"`
}

func (m *Response_MessagesGetMessagesViews) Reset()         { *m = Response_MessagesGetMessagesViews{} }
func (m *Response_MessagesGetMessagesViews) String() string { return proto.CompactTextString(m) }
func (*Response_MessagesGetMessagesViews) ProtoMessage()    {}
func (*Response_MessagesGetMessagesViews) Descriptor() ([]byte, []int) {
	return fileDescriptor_87f3599dbacd6972, []int{3}
}
func (m *Response_MessagesGetMessagesViews) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Response_MessagesGetMessagesViews) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Response_MessagesGetMessagesViews.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Response_MessagesGetMessagesViews) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response_MessagesGetMessagesViews.Merge(m, src)
}
func (m *Response_MessagesGetMessagesViews) XXX_Size() int {
	return m.Size()
}
func (m *Response_MessagesGetMessagesViews) XXX_DiscardUnknown() {
	xxx_messageInfo_Response_MessagesGetMessagesViews.DiscardUnknown(m)
}

var xxx_messageInfo_Response_MessagesGetMessagesViews proto.InternalMessageInfo

func (m *Response_MessagesGetMessagesViews) GetCmd() uint32 {
	if m != nil {
		return m.Cmd
	}
	return 0
}

func (m *Response_MessagesGetMessagesViews) GetMessagesGetMessagesViewsc4C8A55D() *VectorInt {
	if m != nil {
		return m.MessagesGetMessagesViewsc4C8A55D
	}
	return nil
}

func (m *Response_MessagesGetMessagesViews) GetMessagesGetMessagesViews5784D3E1() *Messages_MessageViews {
	if m != nil {
		return m.MessagesGetMessagesViews5784D3E1
	}
	return nil
}

// messages.installStickerSet
type Response_MessagesInstallStickerSet struct {
	Cmd                               uint32                            `protobuf:"varint,1,opt,name=cmd,proto3" json:"cmd,omitempty"`
	MessagesInstallStickerSetc78Fe460 *Messages_StickerSetInstallResult `protobuf:"bytes,2,opt,name=MessagesInstallStickerSetc78Fe460,proto3" json:"MessagesInstallStickerSetc78Fe460,omitempty"`
	MessagesInstallStickerSet7B30C3A6 *Bool                             `protobuf:"bytes,3,opt,name=MessagesInstallStickerSet7B30C3A6,proto3" json:"MessagesInstallStickerSet7B30C3A6,omitempty"`
	XXX_NoUnkeyedLiteral              struct{}                          `json:"-"`
	XXX_unrecognized                  []byte                            `json:"-"`
	XXX_sizecache                     int32                             `json:"-"`
}

func (m *Response_MessagesInstallStickerSet) Reset()         { *m = Response_MessagesInstallStickerSet{} }
func (m *Response_MessagesInstallStickerSet) String() string { return proto.CompactTextString(m) }
func (*Response_MessagesInstallStickerSet) ProtoMessage()    {}
func (*Response_MessagesInstallStickerSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_87f3599dbacd6972, []int{4}
}
func (m *Response_MessagesInstallStickerSet) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Response_MessagesInstallStickerSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Response_MessagesInstallStickerSet.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Response_MessagesInstallStickerSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response_MessagesInstallStickerSet.Merge(m, src)
}
func (m *Response_MessagesInstallStickerSet) XXX_Size() int {
	return m.Size()
}
func (m *Response_MessagesInstallStickerSet) XXX_DiscardUnknown() {
	xxx_messageInfo_Response_MessagesInstallStickerSet.DiscardUnknown(m)
}

var xxx_messageInfo_Response_MessagesInstallStickerSet proto.InternalMessageInfo

func (m *Response_MessagesInstallStickerSet) GetCmd() uint32 {
	if m != nil {
		return m.Cmd
	}
	return 0
}

func (m *Response_MessagesInstallStickerSet) GetMessagesInstallStickerSetc78Fe460() *Messages_StickerSetInstallResult {
	if m != nil {
		return m.MessagesInstallStickerSetc78Fe460
	}
	return nil
}

func (m *Response_MessagesInstallStickerSet) GetMessagesInstallStickerSet7B30C3A6() *Bool {
	if m != nil {
		return m.MessagesInstallStickerSet7B30C3A6
	}
	return nil
}

// messages.readHistory
type Response_MessagesReadHistory struct {
	Cmd                         uint32                     `protobuf:"varint,1,opt,name=cmd,proto3" json:"cmd,omitempty"`
	MessagesReadHistorye306D3A  *Messages_AffectedMessages `protobuf:"bytes,2,opt,name=MessagesReadHistorye306D3A,proto3" json:"MessagesReadHistorye306D3A,omitempty"`
	MessagesReadHistoryb04F2510 *Messages_AffectedHistory  `protobuf:"bytes,3,opt,name=MessagesReadHistoryb04F2510,proto3" json:"MessagesReadHistoryb04F2510,omitempty"`
	XXX_NoUnkeyedLiteral        struct{}                   `json:"-"`
	XXX_unrecognized            []byte                     `json:"-"`
	XXX_sizecache               int32                      `json:"-"`
}

func (m *Response_MessagesReadHistory) Reset()         { *m = Response_MessagesReadHistory{} }
func (m *Response_MessagesReadHistory) String() string { return proto.CompactTextString(m) }
func (*Response_MessagesReadHistory) ProtoMessage()    {}
func (*Response_MessagesReadHistory) Descriptor() ([]byte, []int) {
	return fileDescriptor_87f3599dbacd6972, []int{5}
}
func (m *Response_MessagesReadHistory) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Response_MessagesReadHistory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Response_MessagesReadHistory.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Response_MessagesReadHistory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response_MessagesReadHistory.Merge(m, src)
}
func (m *Response_MessagesReadHistory) XXX_Size() int {
	return m.Size()
}
func (m *Response_MessagesReadHistory) XXX_DiscardUnknown() {
	xxx_messageInfo_Response_MessagesReadHistory.DiscardUnknown(m)
}

var xxx_messageInfo_Response_MessagesReadHistory proto.InternalMessageInfo

func (m *Response_MessagesReadHistory) GetCmd() uint32 {
	if m != nil {
		return m.Cmd
	}
	return 0
}

func (m *Response_MessagesReadHistory) GetMessagesReadHistorye306D3A() *Messages_AffectedMessages {
	if m != nil {
		return m.MessagesReadHistorye306D3A
	}
	return nil
}

func (m *Response_MessagesReadHistory) GetMessagesReadHistoryb04F2510() *Messages_AffectedHistory {
	if m != nil {
		return m.MessagesReadHistoryb04F2510
	}
	return nil
}

// photos.updateProfilePhoto
type Response_PhotosUpdateProfilePhoto struct {
	Cmd                              uint32            `protobuf:"varint,1,opt,name=cmd,proto3" json:"cmd,omitempty"`
	PhotosUpdateProfilePhotof0Bb5152 *UserProfilePhoto `protobuf:"bytes,2,opt,name=PhotosUpdateProfilePhotof0Bb5152,proto3" json:"PhotosUpdateProfilePhotof0Bb5152,omitempty"`
	PhotosUpdateProfilePhoto72D4742C *Photos_Photo     `protobuf:"bytes,3,opt,name=PhotosUpdateProfilePhoto72D4742C,proto3" json:"PhotosUpdateProfilePhoto72D4742C,omitempty"`
	XXX_NoUnkeyedLiteral             struct{}          `json:"-"`
	XXX_unrecognized                 []byte            `json:"-"`
	XXX_sizecache                    int32             `json:"-"`
}

func (m *Response_PhotosUpdateProfilePhoto) Reset()         { *m = Response_PhotosUpdateProfilePhoto{} }
func (m *Response_PhotosUpdateProfilePhoto) String() string { return proto.CompactTextString(m) }
func (*Response_PhotosUpdateProfilePhoto) ProtoMessage()    {}
func (*Response_PhotosUpdateProfilePhoto) Descriptor() ([]byte, []int) {
	return fileDescriptor_87f3599dbacd6972, []int{6}
}
func (m *Response_PhotosUpdateProfilePhoto) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Response_PhotosUpdateProfilePhoto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Response_PhotosUpdateProfilePhoto.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Response_PhotosUpdateProfilePhoto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response_PhotosUpdateProfilePhoto.Merge(m, src)
}
func (m *Response_PhotosUpdateProfilePhoto) XXX_Size() int {
	return m.Size()
}
func (m *Response_PhotosUpdateProfilePhoto) XXX_DiscardUnknown() {
	xxx_messageInfo_Response_PhotosUpdateProfilePhoto.DiscardUnknown(m)
}

var xxx_messageInfo_Response_PhotosUpdateProfilePhoto proto.InternalMessageInfo

func (m *Response_PhotosUpdateProfilePhoto) GetCmd() uint32 {
	if m != nil {
		return m.Cmd
	}
	return 0
}

func (m *Response_PhotosUpdateProfilePhoto) GetPhotosUpdateProfilePhotof0Bb5152() *UserProfilePhoto {
	if m != nil {
		return m.PhotosUpdateProfilePhotof0Bb5152
	}
	return nil
}

func (m *Response_PhotosUpdateProfilePhoto) GetPhotosUpdateProfilePhoto72D4742C() *Photos_Photo {
	if m != nil {
		return m.PhotosUpdateProfilePhoto72D4742C
	}
	return nil
}

// upload.getCdnFileHashes
type Response_UploadGetCdnFileHashes struct {
	Cmd                            uint32              `protobuf:"varint,1,opt,name=cmd,proto3" json:"cmd,omitempty"`
	UploadGetCdnFileHashesf715C87B *Vector_CdnFileHash `protobuf:"bytes,2,opt,name=UploadGetCdnFileHashesf715C87B,proto3" json:"UploadGetCdnFileHashesf715C87B,omitempty"`
	UploadGetCdnFileHashes4Da54231 *Vector_FileHash    `protobuf:"bytes,3,opt,name=UploadGetCdnFileHashes4Da54231,proto3" json:"UploadGetCdnFileHashes4Da54231,omitempty"`
	XXX_NoUnkeyedLiteral           struct{}            `json:"-"`
	XXX_unrecognized               []byte              `json:"-"`
	XXX_sizecache                  int32               `json:"-"`
}

func (m *Response_UploadGetCdnFileHashes) Reset()         { *m = Response_UploadGetCdnFileHashes{} }
func (m *Response_UploadGetCdnFileHashes) String() string { return proto.CompactTextString(m) }
func (*Response_UploadGetCdnFileHashes) ProtoMessage()    {}
func (*Response_UploadGetCdnFileHashes) Descriptor() ([]byte, []int) {
	return fileDescriptor_87f3599dbacd6972, []int{7}
}
func (m *Response_UploadGetCdnFileHashes) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Response_UploadGetCdnFileHashes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Response_UploadGetCdnFileHashes.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Response_UploadGetCdnFileHashes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response_UploadGetCdnFileHashes.Merge(m, src)
}
func (m *Response_UploadGetCdnFileHashes) XXX_Size() int {
	return m.Size()
}
func (m *Response_UploadGetCdnFileHashes) XXX_DiscardUnknown() {
	xxx_messageInfo_Response_UploadGetCdnFileHashes.DiscardUnknown(m)
}

var xxx_messageInfo_Response_UploadGetCdnFileHashes proto.InternalMessageInfo

func (m *Response_UploadGetCdnFileHashes) GetCmd() uint32 {
	if m != nil {
		return m.Cmd
	}
	return 0
}

func (m *Response_UploadGetCdnFileHashes) GetUploadGetCdnFileHashesf715C87B() *Vector_CdnFileHash {
	if m != nil {
		return m.UploadGetCdnFileHashesf715C87B
	}
	return nil
}

func (m *Response_UploadGetCdnFileHashes) GetUploadGetCdnFileHashes4Da54231() *Vector_FileHash {
	if m != nil {
		return m.UploadGetCdnFileHashes4Da54231
	}
	return nil
}

// upload.reuploadCdnFile
type Response_UploadReuploadCdnFile struct {
	Cmd                           uint32              `protobuf:"varint,1,opt,name=cmd,proto3" json:"cmd,omitempty"`
	UploadReuploadCdnFile1Af91C09 *Vector_CdnFileHash `protobuf:"bytes,2,opt,name=UploadReuploadCdnFile1Af91C09,proto3" json:"UploadReuploadCdnFile1Af91C09,omitempty"`
	UploadReuploadCdnFile9B2754A8 *Vector_FileHash    `protobuf:"bytes,3,opt,name=UploadReuploadCdnFile9B2754A8,proto3" json:"UploadReuploadCdnFile9B2754A8,omitempty"`
	XXX_NoUnkeyedLiteral          struct{}            `json:"-"`
	XXX_unrecognized              []byte              `json:"-"`
	XXX_sizecache                 int32               `json:"-"`
}

func (m *Response_UploadReuploadCdnFile) Reset()         { *m = Response_UploadReuploadCdnFile{} }
func (m *Response_UploadReuploadCdnFile) String() string { return proto.CompactTextString(m) }
func (*Response_UploadReuploadCdnFile) ProtoMessage()    {}
func (*Response_UploadReuploadCdnFile) Descriptor() ([]byte, []int) {
	return fileDescriptor_87f3599dbacd6972, []int{8}
}
func (m *Response_UploadReuploadCdnFile) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Response_UploadReuploadCdnFile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Response_UploadReuploadCdnFile.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Response_UploadReuploadCdnFile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response_UploadReuploadCdnFile.Merge(m, src)
}
func (m *Response_UploadReuploadCdnFile) XXX_Size() int {
	return m.Size()
}
func (m *Response_UploadReuploadCdnFile) XXX_DiscardUnknown() {
	xxx_messageInfo_Response_UploadReuploadCdnFile.DiscardUnknown(m)
}

var xxx_messageInfo_Response_UploadReuploadCdnFile proto.InternalMessageInfo

func (m *Response_UploadReuploadCdnFile) GetCmd() uint32 {
	if m != nil {
		return m.Cmd
	}
	return 0
}

func (m *Response_UploadReuploadCdnFile) GetUploadReuploadCdnFile1Af91C09() *Vector_CdnFileHash {
	if m != nil {
		return m.UploadReuploadCdnFile1Af91C09
	}
	return nil
}

func (m *Response_UploadReuploadCdnFile) GetUploadReuploadCdnFile9B2754A8() *Vector_FileHash {
	if m != nil {
		return m.UploadReuploadCdnFile9B2754A8
	}
	return nil
}

func init() {
	proto.RegisterType((*Response_AccountGetWallPapers)(nil), "mtproto.Response_AccountGetWallPapers")
	proto.RegisterType((*Response_ContactsDeleteContacts)(nil), "mtproto.Response_ContactsDeleteContacts")
	proto.RegisterType((*Response_HelpGetAppChangelog)(nil), "mtproto.Response_HelpGetAppChangelog")
	proto.RegisterType((*Response_MessagesGetMessagesViews)(nil), "mtproto.Response_MessagesGetMessagesViews")
	proto.RegisterType((*Response_MessagesInstallStickerSet)(nil), "mtproto.Response_MessagesInstallStickerSet")
	proto.RegisterType((*Response_MessagesReadHistory)(nil), "mtproto.Response_MessagesReadHistory")
	proto.RegisterType((*Response_PhotosUpdateProfilePhoto)(nil), "mtproto.Response_PhotosUpdateProfilePhoto")
	proto.RegisterType((*Response_UploadGetCdnFileHashes)(nil), "mtproto.Response_UploadGetCdnFileHashes")
	proto.RegisterType((*Response_UploadReuploadCdnFile)(nil), "mtproto.Response_UploadReuploadCdnFile")
}

func init() { proto.RegisterFile("schema.service.type.proto", fileDescriptor_87f3599dbacd6972) }

var fileDescriptor_87f3599dbacd6972 = []byte{
	// 783 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x56, 0xcb, 0x6e, 0xeb, 0x44,
	0x18, 0x96, 0x7b, 0x24, 0x90, 0x06, 0x1d, 0xe9, 0xc8, 0x80, 0xd4, 0xa6, 0x6d, 0x68, 0xbd, 0x3a,
	0x2c, 0xc8, 0x71, 0x7c, 0x89, 0x93, 0xa5, 0xe3, 0x34, 0x2d, 0x0b, 0xa4, 0x6a, 0x8e, 0x5a, 0x24,
	0x6e, 0x66, 0x3c, 0xf9, 0x9d, 0x18, 0x1c, 0x8f, 0xe5, 0x99, 0x50, 0x75, 0xcb, 0x9a, 0x07, 0x63,
	0xc9, 0x23, 0x40, 0x9f, 0x00, 0x16, 0x2c, 0x60, 0x03, 0xaa, 0x3b, 0x76, 0x43, 0x32, 0xb6, 0x59,
	0x79, 0x2e, 0xdf, 0x65, 0xbe, 0x3f, 0x33, 0xbf, 0x82, 0x8e, 0x38, 0x5d, 0xc1, 0x9a, 0x0c, 0x38,
	0x14, 0x3f, 0x24, 0x14, 0x06, 0xe2, 0x3e, 0x87, 0x41, 0x5e, 0x30, 0xc1, 0xf4, 0x77, 0xd7, 0xa2,
	0x1c, 0xf4, 0x3e, 0x59, 0x26, 0x62, 0xb5, 0x89, 0x06, 0x94, 0xad, 0xdf, 0x2c, 0xd9, 0x92, 0xbd,
	0x29, 0x97, 0xa3, 0x4d, 0x5c, 0xce, 0xca, 0x49, 0x39, 0x7a, 0xe2, 0xf5, 0x7a, 0x52, 0x52, 0xa4,
	0x03, 0xca, 0x0a, 0x08, 0x1f, 0x25, 0xb9, 0xdc, 0xfb, 0xe0, 0x79, 0x8f, 0xdf, 0x67, 0x54, 0xae,
	0x9e, 0xfc, 0x77, 0x35, 0xac, 0x0e, 0x53, 0xee, 0x1a, 0x7f, 0x68, 0xe8, 0x14, 0x03, 0xcf, 0x59,
	0xc6, 0x21, 0xf4, 0x29, 0x65, 0x9b, 0x4c, 0x5c, 0x82, 0xf8, 0x9c, 0xa4, 0xe9, 0x35, 0xc9, 0xa1,
	0xe0, 0xfa, 0x2b, 0xf4, 0x82, 0xae, 0x17, 0x87, 0xda, 0x99, 0xf6, 0xfa, 0x25, 0x7e, 0x1c, 0xea,
	0x5f, 0xa3, 0x13, 0x15, 0x92, 0x9a, 0x4e, 0x10, 0x13, 0x6a, 0x1d, 0x1e, 0x9c, 0x69, 0xaf, 0xdf,
	0xb3, 0x8e, 0x06, 0x32, 0xe2, 0xe0, 0x16, 0xa8, 0x60, 0x45, 0x58, 0x23, 0x71, 0x2b, 0x5d, 0x0f,
	0xd5, 0xf2, 0x84, 0x44, 0xd1, 0xd0, 0x1b, 0xd9, 0x87, 0x2f, 0x4a, 0xf9, 0xe3, 0x5a, 0x9e, 0x3c,
	0x81, 0x9f, 0xf5, 0x39, 0x6e, 0x15, 0x30, 0x1e, 0x34, 0xf4, 0x51, 0x9d, 0x39, 0x60, 0x99, 0x20,
	0x54, 0xf0, 0x19, 0xa4, 0x20, 0xa0, 0x9a, 0x29, 0x52, 0xdf, 0xa0, 0xbe, 0x1a, 0xeb, 0x4e, 0xfc,
	0xc8, 0x1e, 0x4f, 0x2e, 0x64, 0xee, 0x97, 0xf5, 0xc1, 0xa6, 0x8c, 0xa5, 0xb8, 0x83, 0xa4, 0xdf,
	0xa2, 0x53, 0x35, 0x62, 0x32, 0xf2, 0xcd, 0x0b, 0xd3, 0x94, 0x71, 0x5f, 0xd5, 0xaa, 0x37, 0xf9,
	0x82, 0x08, 0xe0, 0xb8, 0x9d, 0xf6, 0x18, 0xf2, 0xa4, 0x0e, 0x79, 0x05, 0x69, 0x7e, 0x09, 0xc2,
	0xcf, 0xf3, 0x60, 0x45, 0xb2, 0x25, 0xa4, 0x6c, 0xa9, 0x48, 0x88, 0xd1, 0xb1, 0x02, 0x38, 0x31,
	0x87, 0xe6, 0x45, 0x3c, 0x9a, 0xcb, 0x78, 0xfb, 0x07, 0x69, 0x23, 0xe9, 0x5f, 0x29, 0x35, 0xdd,
	0x29, 0x89, 0xbc, 0x79, 0x64, 0xc9, 0x70, 0xbd, 0x5a, 0x73, 0x05, 0x69, 0x1e, 0x6e, 0x23, 0x71,
	0x1b, 0xdd, 0xf8, 0xf1, 0x00, 0x9d, 0xd7, 0x21, 0x3f, 0x03, 0xce, 0xc9, 0x12, 0xf8, 0x25, 0x88,
	0x6a, 0x78, 0x9b, 0xc0, 0x9d, 0xea, 0xb7, 0x0c, 0xd1, 0x59, 0x13, 0x9a, 0x3a, 0xc1, 0xd8, 0x77,
	0xdd, 0x99, 0x8c, 0xfb, 0xfe, 0xee, 0x2d, 0x4e, 0x32, 0x81, 0x3b, 0xc9, 0xfa, 0x77, 0xcd, 0x06,
	0xae, 0x37, 0x76, 0x66, 0xf6, 0xc5, 0x50, 0x66, 0xef, 0xd7, 0x06, 0x6b, 0x89, 0xaa, 0x82, 0x94,
	0x68, 0xdc, 0xa9, 0x63, 0xfc, 0x74, 0x80, 0x8c, 0xbd, 0x22, 0x7c, 0x9a, 0x71, 0x41, 0xd2, 0xf4,
	0xad, 0x48, 0xe8, 0xf7, 0x50, 0xbc, 0x05, 0xa1, 0xa8, 0xc2, 0x1d, 0x3a, 0x6f, 0x84, 0x53, 0x6f,
	0x3c, 0x07, 0x67, 0x64, 0xca, 0x32, 0x7c, 0xbc, 0x7f, 0xca, 0x67, 0xac, 0x24, 0x63, 0xe0, 0x9b,
	0x54, 0xe0, 0x6e, 0x4d, 0xfd, 0xcb, 0x16, 0x63, 0x6f, 0x6a, 0x9b, 0x81, 0xed, 0x8f, 0x64, 0x79,
	0x76, 0x5e, 0x53, 0x37, 0xcf, 0xf8, 0x6b, 0xfb, 0xe2, 0x57, 0x70, 0x0c, 0x64, 0x71, 0x95, 0x70,
	0xc1, 0x8a, 0x7b, 0x45, 0x21, 0x22, 0xd4, 0x53, 0x00, 0xc1, 0x36, 0x47, 0x33, 0xdb, 0x97, 0x15,
	0x30, 0xf6, 0x2b, 0xe0, 0xc7, 0x31, 0x50, 0x01, 0x8b, 0x9a, 0xdb, 0xa2, 0xa2, 0x53, 0x74, 0xac,
	0xd8, 0x8d, 0x4c, 0x67, 0x6e, 0xb9, 0xc3, 0xea, 0x95, 0x9f, 0x37, 0x9b, 0x48, 0x02, 0x6e, 0x53,
	0x31, 0xfe, 0xd1, 0xb6, 0xde, 0xc3, 0xf5, 0x8a, 0x09, 0xc6, 0x9f, 0x5e, 0xe9, 0x75, 0xc1, 0xe2,
	0x24, 0x85, 0x72, 0x49, 0x51, 0x00, 0x40, 0x67, 0x4d, 0xe8, 0xd8, 0x9c, 0x46, 0xee, 0xd0, 0xdd,
	0xef, 0xea, 0x37, 0x1c, 0x8a, 0x6d, 0x20, 0xee, 0x94, 0xd0, 0x49, 0xb3, 0x8d, 0x67, 0xcd, 0x1c,
	0xcf, 0xb1, 0x02, 0x59, 0x88, 0x0f, 0x6b, 0x9b, 0xbc, 0x24, 0x84, 0x1d, 0x16, 0x15, 0xdd, 0xf8,
	0x7b, 0xbb, 0xb7, 0xdf, 0xe4, 0x29, 0x23, 0x8b, 0x4b, 0x10, 0xc1, 0x22, 0x9b, 0x27, 0x29, 0x5c,
	0x11, 0xbe, 0x02, 0x55, 0x3f, 0xa0, 0xa8, 0xaf, 0xc6, 0xc6, 0xde, 0xd0, 0x0d, 0xc6, 0xde, 0x54,
	0xa6, 0x3f, 0xde, 0xed, 0x06, 0x5b, 0x60, 0xdc, 0x21, 0xa1, 0x7f, 0xdb, 0x64, 0xe2, 0xcc, 0x88,
	0xeb, 0x58, 0x76, 0xd5, 0x11, 0x0e, 0x77, 0x4d, 0xba, 0x1c, 0x2a, 0xbe, 0xf1, 0xa7, 0x86, 0xfa,
	0x3b, 0xe1, 0x31, 0x6c, 0xca, 0xaf, 0x24, 0x28, 0xb2, 0x13, 0x74, 0xaa, 0x84, 0x0e, 0xfd, 0x78,
	0x32, 0x0c, 0xcc, 0xc9, 0xff, 0x89, 0xde, 0xae, 0xa0, 0x7f, 0xd3, 0x60, 0x31, 0x99, 0x5a, 0x9e,
	0xeb, 0xf8, 0xe3, 0xce, 0xe0, 0xed, 0xf4, 0xe9, 0xd1, 0xef, 0xbf, 0xf5, 0xb5, 0x9f, 0x1f, 0xfa,
	0xda, 0x2f, 0x0f, 0x7d, 0xed, 0xd7, 0x87, 0xbe, 0xf6, 0x45, 0xf5, 0xf7, 0x2a, 0x7a, 0xa7, 0xfc,
	0xd8, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0x88, 0x82, 0x6f, 0xf6, 0x8b, 0x09, 0x00, 0x00,
}

func (this *Response_AccountGetWallPapers) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 7)
	s = append(s, "&mtproto.Response_AccountGetWallPapers{")
	s = append(s, "Cmd: "+fmt.Sprintf("%#v", this.Cmd)+",\n")
	if this.AccountGetWallPapersc04Cfac2 != nil {
		s = append(s, "AccountGetWallPapersc04Cfac2: "+fmt.Sprintf("%#v", this.AccountGetWallPapersc04Cfac2)+",\n")
	}
	if this.AccountGetWallPapersaabb1763 != nil {
		s = append(s, "AccountGetWallPapersaabb1763: "+fmt.Sprintf("%#v", this.AccountGetWallPapersaabb1763)+",\n")
	}
	if this.XXX_unrecognized != nil {
		s = append(s, "XXX_unrecognized:"+fmt.Sprintf("%#v", this.XXX_unrecognized)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *Response_ContactsDeleteContacts) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 7)
	s = append(s, "&mtproto.Response_ContactsDeleteContacts{")
	s = append(s, "Cmd: "+fmt.Sprintf("%#v", this.Cmd)+",\n")
	if this.ContactsDeleteContacts59Ab389E != nil {
		s = append(s, "ContactsDeleteContacts59Ab389E: "+fmt.Sprintf("%#v", this.ContactsDeleteContacts59Ab389E)+",\n")
	}
	if this.ContactsDeleteContacts96A0E00 != nil {
		s = append(s, "ContactsDeleteContacts96A0E00: "+fmt.Sprintf("%#v", this.ContactsDeleteContacts96A0E00)+",\n")
	}
	if this.XXX_unrecognized != nil {
		s = append(s, "XXX_unrecognized:"+fmt.Sprintf("%#v", this.XXX_unrecognized)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *Response_HelpGetAppChangelog) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 7)
	s = append(s, "&mtproto.Response_HelpGetAppChangelog{")
	s = append(s, "Cmd: "+fmt.Sprintf("%#v", this.Cmd)+",\n")
	if this.HelpGetAppChangelog9010Ef6F != nil {
		s = append(s, "HelpGetAppChangelog9010Ef6F: "+fmt.Sprintf("%#v", this.HelpGetAppChangelog9010Ef6F)+",\n")
	}
	if this.HelpGetAppChangelog5Bab7Fb2 != nil {
		s = append(s, "HelpGetAppChangelog5Bab7Fb2: "+fmt.Sprintf("%#v", this.HelpGetAppChangelog5Bab7Fb2)+",\n")
	}
	if this.XXX_unrecognized != nil {
		s = append(s, "XXX_unrecognized:"+fmt.Sprintf("%#v", this.XXX_unrecognized)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *Response_MessagesGetMessagesViews) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 7)
	s = append(s, "&mtproto.Response_MessagesGetMessagesViews{")
	s = append(s, "Cmd: "+fmt.Sprintf("%#v", this.Cmd)+",\n")
	if this.MessagesGetMessagesViewsc4C8A55D != nil {
		s = append(s, "MessagesGetMessagesViewsc4C8A55D: "+fmt.Sprintf("%#v", this.MessagesGetMessagesViewsc4C8A55D)+",\n")
	}
	if this.MessagesGetMessagesViews5784D3E1 != nil {
		s = append(s, "MessagesGetMessagesViews5784D3E1: "+fmt.Sprintf("%#v", this.MessagesGetMessagesViews5784D3E1)+",\n")
	}
	if this.XXX_unrecognized != nil {
		s = append(s, "XXX_unrecognized:"+fmt.Sprintf("%#v", this.XXX_unrecognized)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *Response_MessagesInstallStickerSet) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 7)
	s = append(s, "&mtproto.Response_MessagesInstallStickerSet{")
	s = append(s, "Cmd: "+fmt.Sprintf("%#v", this.Cmd)+",\n")
	if this.MessagesInstallStickerSetc78Fe460 != nil {
		s = append(s, "MessagesInstallStickerSetc78Fe460: "+fmt.Sprintf("%#v", this.MessagesInstallStickerSetc78Fe460)+",\n")
	}
	if this.MessagesInstallStickerSet7B30C3A6 != nil {
		s = append(s, "MessagesInstallStickerSet7B30C3A6: "+fmt.Sprintf("%#v", this.MessagesInstallStickerSet7B30C3A6)+",\n")
	}
	if this.XXX_unrecognized != nil {
		s = append(s, "XXX_unrecognized:"+fmt.Sprintf("%#v", this.XXX_unrecognized)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *Response_MessagesReadHistory) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 7)
	s = append(s, "&mtproto.Response_MessagesReadHistory{")
	s = append(s, "Cmd: "+fmt.Sprintf("%#v", this.Cmd)+",\n")
	if this.MessagesReadHistorye306D3A != nil {
		s = append(s, "MessagesReadHistorye306D3A: "+fmt.Sprintf("%#v", this.MessagesReadHistorye306D3A)+",\n")
	}
	if this.MessagesReadHistoryb04F2510 != nil {
		s = append(s, "MessagesReadHistoryb04F2510: "+fmt.Sprintf("%#v", this.MessagesReadHistoryb04F2510)+",\n")
	}
	if this.XXX_unrecognized != nil {
		s = append(s, "XXX_unrecognized:"+fmt.Sprintf("%#v", this.XXX_unrecognized)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *Response_PhotosUpdateProfilePhoto) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 7)
	s = append(s, "&mtproto.Response_PhotosUpdateProfilePhoto{")
	s = append(s, "Cmd: "+fmt.Sprintf("%#v", this.Cmd)+",\n")
	if this.PhotosUpdateProfilePhotof0Bb5152 != nil {
		s = append(s, "PhotosUpdateProfilePhotof0Bb5152: "+fmt.Sprintf("%#v", this.PhotosUpdateProfilePhotof0Bb5152)+",\n")
	}
	if this.PhotosUpdateProfilePhoto72D4742C != nil {
		s = append(s, "PhotosUpdateProfilePhoto72D4742C: "+fmt.Sprintf("%#v", this.PhotosUpdateProfilePhoto72D4742C)+",\n")
	}
	if this.XXX_unrecognized != nil {
		s = append(s, "XXX_unrecognized:"+fmt.Sprintf("%#v", this.XXX_unrecognized)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *Response_UploadGetCdnFileHashes) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 7)
	s = append(s, "&mtproto.Response_UploadGetCdnFileHashes{")
	s = append(s, "Cmd: "+fmt.Sprintf("%#v", this.Cmd)+",\n")
	if this.UploadGetCdnFileHashesf715C87B != nil {
		s = append(s, "UploadGetCdnFileHashesf715C87B: "+fmt.Sprintf("%#v", this.UploadGetCdnFileHashesf715C87B)+",\n")
	}
	if this.UploadGetCdnFileHashes4Da54231 != nil {
		s = append(s, "UploadGetCdnFileHashes4Da54231: "+fmt.Sprintf("%#v", this.UploadGetCdnFileHashes4Da54231)+",\n")
	}
	if this.XXX_unrecognized != nil {
		s = append(s, "XXX_unrecognized:"+fmt.Sprintf("%#v", this.XXX_unrecognized)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *Response_UploadReuploadCdnFile) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 7)
	s = append(s, "&mtproto.Response_UploadReuploadCdnFile{")
	s = append(s, "Cmd: "+fmt.Sprintf("%#v", this.Cmd)+",\n")
	if this.UploadReuploadCdnFile1Af91C09 != nil {
		s = append(s, "UploadReuploadCdnFile1Af91C09: "+fmt.Sprintf("%#v", this.UploadReuploadCdnFile1Af91C09)+",\n")
	}
	if this.UploadReuploadCdnFile9B2754A8 != nil {
		s = append(s, "UploadReuploadCdnFile9B2754A8: "+fmt.Sprintf("%#v", this.UploadReuploadCdnFile9B2754A8)+",\n")
	}
	if this.XXX_unrecognized != nil {
		s = append(s, "XXX_unrecognized:"+fmt.Sprintf("%#v", this.XXX_unrecognized)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringSchemaServiceType(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *Response_AccountGetWallPapers) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Response_AccountGetWallPapers) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Response_AccountGetWallPapers) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.AccountGetWallPapersaabb1763 != nil {
		{
			size, err := m.AccountGetWallPapersaabb1763.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSchemaServiceType(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.AccountGetWallPapersc04Cfac2 != nil {
		{
			size, err := m.AccountGetWallPapersc04Cfac2.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSchemaServiceType(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.Cmd != 0 {
		i = encodeVarintSchemaServiceType(dAtA, i, uint64(m.Cmd))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Response_ContactsDeleteContacts) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Response_ContactsDeleteContacts) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Response_ContactsDeleteContacts) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.ContactsDeleteContacts96A0E00 != nil {
		{
			size, err := m.ContactsDeleteContacts96A0E00.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSchemaServiceType(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.ContactsDeleteContacts59Ab389E != nil {
		{
			size, err := m.ContactsDeleteContacts59Ab389E.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSchemaServiceType(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.Cmd != 0 {
		i = encodeVarintSchemaServiceType(dAtA, i, uint64(m.Cmd))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Response_HelpGetAppChangelog) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Response_HelpGetAppChangelog) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Response_HelpGetAppChangelog) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.HelpGetAppChangelog5Bab7Fb2 != nil {
		{
			size, err := m.HelpGetAppChangelog5Bab7Fb2.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSchemaServiceType(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.HelpGetAppChangelog9010Ef6F != nil {
		{
			size, err := m.HelpGetAppChangelog9010Ef6F.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSchemaServiceType(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.Cmd != 0 {
		i = encodeVarintSchemaServiceType(dAtA, i, uint64(m.Cmd))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Response_MessagesGetMessagesViews) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Response_MessagesGetMessagesViews) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Response_MessagesGetMessagesViews) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.MessagesGetMessagesViews5784D3E1 != nil {
		{
			size, err := m.MessagesGetMessagesViews5784D3E1.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSchemaServiceType(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.MessagesGetMessagesViewsc4C8A55D != nil {
		{
			size, err := m.MessagesGetMessagesViewsc4C8A55D.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSchemaServiceType(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.Cmd != 0 {
		i = encodeVarintSchemaServiceType(dAtA, i, uint64(m.Cmd))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Response_MessagesInstallStickerSet) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Response_MessagesInstallStickerSet) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Response_MessagesInstallStickerSet) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.MessagesInstallStickerSet7B30C3A6 != nil {
		{
			size, err := m.MessagesInstallStickerSet7B30C3A6.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSchemaServiceType(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.MessagesInstallStickerSetc78Fe460 != nil {
		{
			size, err := m.MessagesInstallStickerSetc78Fe460.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSchemaServiceType(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.Cmd != 0 {
		i = encodeVarintSchemaServiceType(dAtA, i, uint64(m.Cmd))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Response_MessagesReadHistory) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Response_MessagesReadHistory) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Response_MessagesReadHistory) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.MessagesReadHistoryb04F2510 != nil {
		{
			size, err := m.MessagesReadHistoryb04F2510.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSchemaServiceType(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.MessagesReadHistorye306D3A != nil {
		{
			size, err := m.MessagesReadHistorye306D3A.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSchemaServiceType(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.Cmd != 0 {
		i = encodeVarintSchemaServiceType(dAtA, i, uint64(m.Cmd))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Response_PhotosUpdateProfilePhoto) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Response_PhotosUpdateProfilePhoto) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Response_PhotosUpdateProfilePhoto) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.PhotosUpdateProfilePhoto72D4742C != nil {
		{
			size, err := m.PhotosUpdateProfilePhoto72D4742C.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSchemaServiceType(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.PhotosUpdateProfilePhotof0Bb5152 != nil {
		{
			size, err := m.PhotosUpdateProfilePhotof0Bb5152.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSchemaServiceType(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.Cmd != 0 {
		i = encodeVarintSchemaServiceType(dAtA, i, uint64(m.Cmd))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Response_UploadGetCdnFileHashes) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Response_UploadGetCdnFileHashes) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Response_UploadGetCdnFileHashes) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.UploadGetCdnFileHashes4Da54231 != nil {
		{
			size, err := m.UploadGetCdnFileHashes4Da54231.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSchemaServiceType(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.UploadGetCdnFileHashesf715C87B != nil {
		{
			size, err := m.UploadGetCdnFileHashesf715C87B.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSchemaServiceType(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.Cmd != 0 {
		i = encodeVarintSchemaServiceType(dAtA, i, uint64(m.Cmd))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Response_UploadReuploadCdnFile) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Response_UploadReuploadCdnFile) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Response_UploadReuploadCdnFile) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.UploadReuploadCdnFile9B2754A8 != nil {
		{
			size, err := m.UploadReuploadCdnFile9B2754A8.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSchemaServiceType(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.UploadReuploadCdnFile1Af91C09 != nil {
		{
			size, err := m.UploadReuploadCdnFile1Af91C09.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSchemaServiceType(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.Cmd != 0 {
		i = encodeVarintSchemaServiceType(dAtA, i, uint64(m.Cmd))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintSchemaServiceType(dAtA []byte, offset int, v uint64) int {
	offset -= sovSchemaServiceType(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Response_AccountGetWallPapers) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Cmd != 0 {
		n += 1 + sovSchemaServiceType(uint64(m.Cmd))
	}
	if m.AccountGetWallPapersc04Cfac2 != nil {
		l = m.AccountGetWallPapersc04Cfac2.Size()
		n += 1 + l + sovSchemaServiceType(uint64(l))
	}
	if m.AccountGetWallPapersaabb1763 != nil {
		l = m.AccountGetWallPapersaabb1763.Size()
		n += 1 + l + sovSchemaServiceType(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *Response_ContactsDeleteContacts) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Cmd != 0 {
		n += 1 + sovSchemaServiceType(uint64(m.Cmd))
	}
	if m.ContactsDeleteContacts59Ab389E != nil {
		l = m.ContactsDeleteContacts59Ab389E.Size()
		n += 1 + l + sovSchemaServiceType(uint64(l))
	}
	if m.ContactsDeleteContacts96A0E00 != nil {
		l = m.ContactsDeleteContacts96A0E00.Size()
		n += 1 + l + sovSchemaServiceType(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *Response_HelpGetAppChangelog) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Cmd != 0 {
		n += 1 + sovSchemaServiceType(uint64(m.Cmd))
	}
	if m.HelpGetAppChangelog9010Ef6F != nil {
		l = m.HelpGetAppChangelog9010Ef6F.Size()
		n += 1 + l + sovSchemaServiceType(uint64(l))
	}
	if m.HelpGetAppChangelog5Bab7Fb2 != nil {
		l = m.HelpGetAppChangelog5Bab7Fb2.Size()
		n += 1 + l + sovSchemaServiceType(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *Response_MessagesGetMessagesViews) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Cmd != 0 {
		n += 1 + sovSchemaServiceType(uint64(m.Cmd))
	}
	if m.MessagesGetMessagesViewsc4C8A55D != nil {
		l = m.MessagesGetMessagesViewsc4C8A55D.Size()
		n += 1 + l + sovSchemaServiceType(uint64(l))
	}
	if m.MessagesGetMessagesViews5784D3E1 != nil {
		l = m.MessagesGetMessagesViews5784D3E1.Size()
		n += 1 + l + sovSchemaServiceType(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *Response_MessagesInstallStickerSet) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Cmd != 0 {
		n += 1 + sovSchemaServiceType(uint64(m.Cmd))
	}
	if m.MessagesInstallStickerSetc78Fe460 != nil {
		l = m.MessagesInstallStickerSetc78Fe460.Size()
		n += 1 + l + sovSchemaServiceType(uint64(l))
	}
	if m.MessagesInstallStickerSet7B30C3A6 != nil {
		l = m.MessagesInstallStickerSet7B30C3A6.Size()
		n += 1 + l + sovSchemaServiceType(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *Response_MessagesReadHistory) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Cmd != 0 {
		n += 1 + sovSchemaServiceType(uint64(m.Cmd))
	}
	if m.MessagesReadHistorye306D3A != nil {
		l = m.MessagesReadHistorye306D3A.Size()
		n += 1 + l + sovSchemaServiceType(uint64(l))
	}
	if m.MessagesReadHistoryb04F2510 != nil {
		l = m.MessagesReadHistoryb04F2510.Size()
		n += 1 + l + sovSchemaServiceType(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *Response_PhotosUpdateProfilePhoto) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Cmd != 0 {
		n += 1 + sovSchemaServiceType(uint64(m.Cmd))
	}
	if m.PhotosUpdateProfilePhotof0Bb5152 != nil {
		l = m.PhotosUpdateProfilePhotof0Bb5152.Size()
		n += 1 + l + sovSchemaServiceType(uint64(l))
	}
	if m.PhotosUpdateProfilePhoto72D4742C != nil {
		l = m.PhotosUpdateProfilePhoto72D4742C.Size()
		n += 1 + l + sovSchemaServiceType(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *Response_UploadGetCdnFileHashes) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Cmd != 0 {
		n += 1 + sovSchemaServiceType(uint64(m.Cmd))
	}
	if m.UploadGetCdnFileHashesf715C87B != nil {
		l = m.UploadGetCdnFileHashesf715C87B.Size()
		n += 1 + l + sovSchemaServiceType(uint64(l))
	}
	if m.UploadGetCdnFileHashes4Da54231 != nil {
		l = m.UploadGetCdnFileHashes4Da54231.Size()
		n += 1 + l + sovSchemaServiceType(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *Response_UploadReuploadCdnFile) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Cmd != 0 {
		n += 1 + sovSchemaServiceType(uint64(m.Cmd))
	}
	if m.UploadReuploadCdnFile1Af91C09 != nil {
		l = m.UploadReuploadCdnFile1Af91C09.Size()
		n += 1 + l + sovSchemaServiceType(uint64(l))
	}
	if m.UploadReuploadCdnFile9B2754A8 != nil {
		l = m.UploadReuploadCdnFile9B2754A8.Size()
		n += 1 + l + sovSchemaServiceType(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovSchemaServiceType(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozSchemaServiceType(x uint64) (n int) {
	return sovSchemaServiceType(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Response_AccountGetWallPapers) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSchemaServiceType
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Response_AccountGetWallPapers: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Response_AccountGetWallPapers: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cmd", wireType)
			}
			m.Cmd = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchemaServiceType
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Cmd |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccountGetWallPapersc04Cfac2", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchemaServiceType
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSchemaServiceType
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSchemaServiceType
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.AccountGetWallPapersc04Cfac2 == nil {
				m.AccountGetWallPapersc04Cfac2 = &Vector_WallPaper{}
			}
			if err := m.AccountGetWallPapersc04Cfac2.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccountGetWallPapersaabb1763", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchemaServiceType
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSchemaServiceType
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSchemaServiceType
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.AccountGetWallPapersaabb1763 == nil {
				m.AccountGetWallPapersaabb1763 = &Account_WallPapers{}
			}
			if err := m.AccountGetWallPapersaabb1763.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSchemaServiceType(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSchemaServiceType
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthSchemaServiceType
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Response_ContactsDeleteContacts) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSchemaServiceType
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Response_ContactsDeleteContacts: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Response_ContactsDeleteContacts: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cmd", wireType)
			}
			m.Cmd = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchemaServiceType
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Cmd |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContactsDeleteContacts59Ab389E", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchemaServiceType
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSchemaServiceType
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSchemaServiceType
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ContactsDeleteContacts59Ab389E == nil {
				m.ContactsDeleteContacts59Ab389E = &Bool{}
			}
			if err := m.ContactsDeleteContacts59Ab389E.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContactsDeleteContacts96A0E00", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchemaServiceType
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSchemaServiceType
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSchemaServiceType
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ContactsDeleteContacts96A0E00 == nil {
				m.ContactsDeleteContacts96A0E00 = &Updates{}
			}
			if err := m.ContactsDeleteContacts96A0E00.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSchemaServiceType(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSchemaServiceType
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthSchemaServiceType
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Response_HelpGetAppChangelog) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSchemaServiceType
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Response_HelpGetAppChangelog: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Response_HelpGetAppChangelog: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cmd", wireType)
			}
			m.Cmd = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchemaServiceType
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Cmd |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HelpGetAppChangelog9010Ef6F", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchemaServiceType
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSchemaServiceType
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSchemaServiceType
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.HelpGetAppChangelog9010Ef6F == nil {
				m.HelpGetAppChangelog9010Ef6F = &Updates{}
			}
			if err := m.HelpGetAppChangelog9010Ef6F.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HelpGetAppChangelog5Bab7Fb2", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchemaServiceType
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSchemaServiceType
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSchemaServiceType
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.HelpGetAppChangelog5Bab7Fb2 == nil {
				m.HelpGetAppChangelog5Bab7Fb2 = &Help_AppChangelog{}
			}
			if err := m.HelpGetAppChangelog5Bab7Fb2.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSchemaServiceType(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSchemaServiceType
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthSchemaServiceType
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Response_MessagesGetMessagesViews) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSchemaServiceType
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Response_MessagesGetMessagesViews: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Response_MessagesGetMessagesViews: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cmd", wireType)
			}
			m.Cmd = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchemaServiceType
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Cmd |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MessagesGetMessagesViewsc4C8A55D", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchemaServiceType
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSchemaServiceType
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSchemaServiceType
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.MessagesGetMessagesViewsc4C8A55D == nil {
				m.MessagesGetMessagesViewsc4C8A55D = &VectorInt{}
			}
			if err := m.MessagesGetMessagesViewsc4C8A55D.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MessagesGetMessagesViews5784D3E1", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchemaServiceType
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSchemaServiceType
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSchemaServiceType
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.MessagesGetMessagesViews5784D3E1 == nil {
				m.MessagesGetMessagesViews5784D3E1 = &Messages_MessageViews{}
			}
			if err := m.MessagesGetMessagesViews5784D3E1.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSchemaServiceType(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSchemaServiceType
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthSchemaServiceType
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Response_MessagesInstallStickerSet) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSchemaServiceType
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Response_MessagesInstallStickerSet: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Response_MessagesInstallStickerSet: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cmd", wireType)
			}
			m.Cmd = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchemaServiceType
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Cmd |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MessagesInstallStickerSetc78Fe460", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchemaServiceType
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSchemaServiceType
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSchemaServiceType
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.MessagesInstallStickerSetc78Fe460 == nil {
				m.MessagesInstallStickerSetc78Fe460 = &Messages_StickerSetInstallResult{}
			}
			if err := m.MessagesInstallStickerSetc78Fe460.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MessagesInstallStickerSet7B30C3A6", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchemaServiceType
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSchemaServiceType
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSchemaServiceType
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.MessagesInstallStickerSet7B30C3A6 == nil {
				m.MessagesInstallStickerSet7B30C3A6 = &Bool{}
			}
			if err := m.MessagesInstallStickerSet7B30C3A6.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSchemaServiceType(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSchemaServiceType
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthSchemaServiceType
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Response_MessagesReadHistory) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSchemaServiceType
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Response_MessagesReadHistory: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Response_MessagesReadHistory: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cmd", wireType)
			}
			m.Cmd = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchemaServiceType
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Cmd |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MessagesReadHistorye306D3A", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchemaServiceType
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSchemaServiceType
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSchemaServiceType
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.MessagesReadHistorye306D3A == nil {
				m.MessagesReadHistorye306D3A = &Messages_AffectedMessages{}
			}
			if err := m.MessagesReadHistorye306D3A.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MessagesReadHistoryb04F2510", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchemaServiceType
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSchemaServiceType
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSchemaServiceType
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.MessagesReadHistoryb04F2510 == nil {
				m.MessagesReadHistoryb04F2510 = &Messages_AffectedHistory{}
			}
			if err := m.MessagesReadHistoryb04F2510.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSchemaServiceType(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSchemaServiceType
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthSchemaServiceType
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Response_PhotosUpdateProfilePhoto) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSchemaServiceType
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Response_PhotosUpdateProfilePhoto: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Response_PhotosUpdateProfilePhoto: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cmd", wireType)
			}
			m.Cmd = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchemaServiceType
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Cmd |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PhotosUpdateProfilePhotof0Bb5152", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchemaServiceType
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSchemaServiceType
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSchemaServiceType
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.PhotosUpdateProfilePhotof0Bb5152 == nil {
				m.PhotosUpdateProfilePhotof0Bb5152 = &UserProfilePhoto{}
			}
			if err := m.PhotosUpdateProfilePhotof0Bb5152.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PhotosUpdateProfilePhoto72D4742C", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchemaServiceType
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSchemaServiceType
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSchemaServiceType
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.PhotosUpdateProfilePhoto72D4742C == nil {
				m.PhotosUpdateProfilePhoto72D4742C = &Photos_Photo{}
			}
			if err := m.PhotosUpdateProfilePhoto72D4742C.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSchemaServiceType(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSchemaServiceType
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthSchemaServiceType
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Response_UploadGetCdnFileHashes) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSchemaServiceType
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Response_UploadGetCdnFileHashes: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Response_UploadGetCdnFileHashes: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cmd", wireType)
			}
			m.Cmd = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchemaServiceType
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Cmd |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UploadGetCdnFileHashesf715C87B", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchemaServiceType
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSchemaServiceType
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSchemaServiceType
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.UploadGetCdnFileHashesf715C87B == nil {
				m.UploadGetCdnFileHashesf715C87B = &Vector_CdnFileHash{}
			}
			if err := m.UploadGetCdnFileHashesf715C87B.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UploadGetCdnFileHashes4Da54231", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchemaServiceType
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSchemaServiceType
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSchemaServiceType
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.UploadGetCdnFileHashes4Da54231 == nil {
				m.UploadGetCdnFileHashes4Da54231 = &Vector_FileHash{}
			}
			if err := m.UploadGetCdnFileHashes4Da54231.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSchemaServiceType(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSchemaServiceType
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthSchemaServiceType
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Response_UploadReuploadCdnFile) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSchemaServiceType
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Response_UploadReuploadCdnFile: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Response_UploadReuploadCdnFile: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cmd", wireType)
			}
			m.Cmd = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchemaServiceType
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Cmd |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UploadReuploadCdnFile1Af91C09", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchemaServiceType
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSchemaServiceType
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSchemaServiceType
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.UploadReuploadCdnFile1Af91C09 == nil {
				m.UploadReuploadCdnFile1Af91C09 = &Vector_CdnFileHash{}
			}
			if err := m.UploadReuploadCdnFile1Af91C09.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UploadReuploadCdnFile9B2754A8", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchemaServiceType
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSchemaServiceType
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSchemaServiceType
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.UploadReuploadCdnFile9B2754A8 == nil {
				m.UploadReuploadCdnFile9B2754A8 = &Vector_FileHash{}
			}
			if err := m.UploadReuploadCdnFile9B2754A8.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSchemaServiceType(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSchemaServiceType
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthSchemaServiceType
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipSchemaServiceType(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowSchemaServiceType
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSchemaServiceType
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSchemaServiceType
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthSchemaServiceType
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupSchemaServiceType
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthSchemaServiceType
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthSchemaServiceType        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowSchemaServiceType          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupSchemaServiceType = fmt.Errorf("proto: unexpected end of group")
)
