// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: schema.error.proto

package mtproto

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type RpcErrorCode int32

const (
	RpcErrorCode_OK                 RpcErrorCode = 0
	RpcErrorCode_BASE_NUMBER        RpcErrorCode = 10000
	RpcErrorCode_UNKNOWN            RpcErrorCode = 10001
	RpcErrorCode_ErrorFormatUNKNOWN RpcErrorCode = 10002
	RpcErrorCode_TIMEOUT            RpcErrorCode = 10003
	//    303 SEE_OTHER
	//    The request must be repeated, but directed to a different data center.
	//    FILE_MIGRATE_X: the file to be accessed is currently stored in a different data center.
	//    PHONE_MIGRATE_X: the phone number a user is trying to use for authorization is associated with a different data center.
	//    NETWORK_MIGRATE_X: the source IP address is associated with a different data center (for registration)
	//    USER_MIGRATE_X: the user whose identity is being used to execute queries is associated with a different data center (for registration)
	RpcErrorCode_SEE_OTHER                 RpcErrorCode = 3030000
	RpcErrorCode_SEE_OTHER_FILE_MIGRATE    RpcErrorCode = 3031000
	RpcErrorCode_SEE_OTHER_PHONE_MIGRATE   RpcErrorCode = 3032000
	RpcErrorCode_SEE_OTHER_NETWORK_MIGRATE RpcErrorCode = 3033000
	RpcErrorCode_SEE_OTHER_USER_MIGRATE    RpcErrorCode = 3034000
	RpcErrorCode_SEE_OTHER_X_MAX           RpcErrorCode = 3034001
	//    400 BAD_REQUEST
	//    The query contains errors. In the event that a request was created using a form and contains user generated data, the user should be notified that the data must be corrected before the query is repeated.
	//
	//    Examples of Errors:
	//    FIRSTNAME_INVALID: The first name is invalid
	//    LASTNAME_INVALID: The last name is invalid
	//    PHONE_NUMBER_INVALID: The phone number is invalid
	//    PHONE_CODE_HASH_EMPTY: phone_code_hash is missing
	//    PHONE_CODE_EMPTY: phone_code is missing
	//    PHONE_CODE_EXPIRED: The confirmation code has expired
	//    API_ID_INVALID: The api_id/api_hash combination is invalid
	//    PHONE_NUMBER_OCCUPIED: The phone number is already in use
	//    PHONE_NUMBER_UNOCCUPIED: The phone number is not yet being used
	//    USERS_TOO_FEW: Not enough users (to create a chat, for example)
	//    USERS_TOO_MUCH: The maximum number of users has been exceeded (to create a chat, for example)
	//    TYPE_CONSTRUCTOR_INVALID: The type constructor is invalid
	//    FILE_PART_INVALID: The file part number is invalid
	//    FILE_PARTS_INVALID: The number of file parts is invalid
	//    FILE_PART_Х_MISSING: Part X (where X is a number) of the file is missing from storage
	//    MD5_CHECKSUM_INVALID: The MD5 checksums do not match
	//    PHOTO_INVALID_DIMENSIONS: The photo dimensions are invalid
	//    FIELD_NAME_INVALID: The field with the name FIELD_NAME is invalid
	//    FIELD_NAME_EMPTY: The field with the name FIELD_NAME is missing
	//    MSG_WAIT_FAILED: A waiting call returned an error
	RpcErrorCode_BAD_REQUEST                                   RpcErrorCode = 4000000
	RpcErrorCode_BAD_REQUEST_FIRSTNAME_INVALID                 RpcErrorCode = 4000100
	RpcErrorCode_BAD_REQUEST_LASTNAME_INVALID                  RpcErrorCode = 4000200
	RpcErrorCode_BAD_REQUEST_PHONE_NUMBER_INVALID              RpcErrorCode = 4000300
	RpcErrorCode_BAD_REQUEST_PHONE_CODE_HASH_EMPTY             RpcErrorCode = 4000400
	RpcErrorCode_BAD_REQUEST_PHONE_CODE_EMPTY                  RpcErrorCode = 4000500
	RpcErrorCode_BAD_REQUEST_PHONE_CODE_INVALID                RpcErrorCode = 4000501
	RpcErrorCode_BAD_REQUEST_PHONE_CODE_EXPIRED                RpcErrorCode = 4000600
	RpcErrorCode_BAD_REQUEST_API_ID_INVALID                    RpcErrorCode = 4000700
	RpcErrorCode_BAD_REQUEST_PHONE_NUMBER_OCCUPIED             RpcErrorCode = 4000800
	RpcErrorCode_BAD_REQUEST_PHONE_NUMBER_UNOCCUPIED           RpcErrorCode = 4000900
	RpcErrorCode_BAD_REQUEST_USERS_TOO_FEW                     RpcErrorCode = 4001000
	RpcErrorCode_BAD_REQUEST_USERS_TOO_MUCH                    RpcErrorCode = 4001100
	RpcErrorCode_BAD_REQUEST_TYPE_CONSTRUCTOR_INVALID          RpcErrorCode = 4001200
	RpcErrorCode_BAD_REQUEST_FILE_PART_INVALID                 RpcErrorCode = 4001300
	RpcErrorCode_BAD_REQUEST_FILE_PARTS_INVALID                RpcErrorCode = 4001400
	RpcErrorCode_BAD_REQUEST_FILE_PART_X_MISSING               RpcErrorCode = 4001500
	RpcErrorCode_BAD_REQUEST_MD5_CHECKSUM_INVALID              RpcErrorCode = 4001600
	RpcErrorCode_BAD_REQUEST_PHOTO_INVALID_DIMENSIONS          RpcErrorCode = 4001700
	RpcErrorCode_BAD_REQUEST_FIELD_NAME_INVALID                RpcErrorCode = 4001800
	RpcErrorCode_BAD_REQUEST_FIELD_NAME_EMPTY                  RpcErrorCode = 4001900
	RpcErrorCode_BAD_REQUEST_MSG_WAIT_FAILED                   RpcErrorCode = 4002000
	RpcErrorCode_BAD_REQUEST_PHONE_NUMBER_BANNED               RpcErrorCode = 4002001
	RpcErrorCode_BAD_REQUEST_PHONE_NUMBER_FLOOD                RpcErrorCode = 4002002
	RpcErrorCode_BAD_REQUEST_PHONE_PASSWORD_FLOOD              RpcErrorCode = 4002003
	RpcErrorCode_BAD_REQUEST_PHONE_PASSWORD_PROTECTED          RpcErrorCode = 4002004
	RpcErrorCode_BAD_REQUEST_AUTH_KEY_PERM_EMPTY               RpcErrorCode = 4002005
	RpcErrorCode_BAD_REQUEST_API_ID_PUBLISHED_FLOOD            RpcErrorCode = 4002006
	RpcErrorCode_BAD_REQUEST_PHONE_NUMBER_APP_SIGNUP_FORBIDDEN RpcErrorCode = 4002007
	RpcErrorCode_BAD_REQUEST_INPUT_CONSTRUCTOR_INVALID         RpcErrorCode = 4002008
	RpcErrorCode_BAD_REQUEST_PEER_ID_INVALID                   RpcErrorCode = 4002009
	RpcErrorCode_BAD_REQUEST_TOKEN_INVALID                     RpcErrorCode = 4002010
	RpcErrorCode_BAD_REQUEST_NO_PROMISSION                     RpcErrorCode = 4002011
	RpcErrorCode_BAD_REQUEST_STICKERSET_INVALID                RpcErrorCode = 4002012
	//    400	CONTACT_ID_INVALID	The provided contact ID is invalid
	//    400	CONTACT_NAME_EMPTY	Contact name empty
	//    400	MSG_ID_INVALID	Invalid message ID provided
	RpcErrorCode_BAD_REQUEST_CONTACT_ID_INVALID RpcErrorCode = 4002013
	RpcErrorCode_BAD_REQUEST_CONTACT_NAME_EMPTY RpcErrorCode = 4002014
	RpcErrorCode_BAD_REQUEST_MSG_ID_INVALID     RpcErrorCode = 4002015
	//    401	AUTH_KEY_PERM_EMPTY	The temporary auth key must be binded to the permanent auth key to use these methods.
	//    400	CDN_METHOD_INVALID	You can't call this method in a CDN DC
	//    400	DATE_EMPTY	Date empty
	//    400	PERSISTENT_TIMESTAMP_EMPTY	Persistent timestamp empty
	//    400	PERSISTENT_TIMESTAMP_INVALID	Persistent timestamp invalid
	RpcErrorCode_BAD_REQUEST_CDN_METHOD_INVALID           RpcErrorCode = 4002016
	RpcErrorCode_BAD_REQUEST_DATE_EMPTY                   RpcErrorCode = 4002017
	RpcErrorCode_BAD_REQUEST_PERSISTENT_TIMESTAMP_EMPTY   RpcErrorCode = 4002018
	RpcErrorCode_BAD_REQUEST_PERSISTENT_TIMESTAMP_INVALID RpcErrorCode = 4002019
	//    400	QUERY_TOO_SHORT	The query string is too short
	//    400	SEARCH_QUERY_EMPTY	The search query is empty
	RpcErrorCode_BAD_REQUEST_QUERY_TOO_SHORT    RpcErrorCode = 4002020
	RpcErrorCode_BAD_REQUEST_SEARCH_QUERY_EMPTY RpcErrorCode = 4002021
	//    400	USERNAME_INVALID	Unacceptable username
	//    400 USERNAME_OCCUPIED UsernameInUse
	RpcErrorCode_BAD_REQUEST_USERNAME_INVALID      RpcErrorCode = 4002022
	RpcErrorCode_BAD_REQUEST_USERNAME_OCCUPIED     RpcErrorCode = 4002023
	RpcErrorCode_BAD_REQUEST_USERNAME_NOT_MODIFIED RpcErrorCode = 4002024
	//    400	CHANNEL_INVALID	The provided channel is invalid
	//    400	CHANNEL_PRIVATE	You haven't joined this channel/supergroup
	//    400	CHAT_ADMIN_REQUIRED	You must be an admin in this chat to do this
	//    400	INPUT_CONSTRUCTOR_INVALID	The provided constructor is invalid
	//    400	INPUT_USER_DEACTIVATED	The specified user was deleted
	//    400	MSG_ID_INVALID	Invalid message ID provided
	//    400	PEER_ID_INVALID	The provided peer id is invalid
	//    400	PEER_ID_NOT_SUPPORTED	The provided peer ID is not supported
	//    400	SEARCH_QUERY_EMPTY	The search query is empty
	//    400	USER_ID_INVALID	The provided user ID is invalid
	//    400	CALL_ALREADY_ACCEPTED	The call was already accepted
	//    400	CALL_ALREADY_DECLINED	The call was already declined
	//    400	CALL_PEER_INVALID	The provided call peer object is invalid
	//    400	CALL_PROTOCOL_FLAGS_INVALID	Call protocol flags invalid
	//    400	DATA_JSON_INVALID	The provided JSON data is invalid
	RpcErrorCode_BAD_REQUEST_CHANNEL_INVALID               RpcErrorCode = 4002025
	RpcErrorCode_BAD_REQUEST_CHANNEL_PRIVATE               RpcErrorCode = 4002026
	RpcErrorCode_BAD_REQUEST_CHAT_ADMIN_REQUIRED           RpcErrorCode = 4002027
	RpcErrorCode_BAD_REQUEST_PEER_ID_NOT_SUPPORTED         RpcErrorCode = 4002028
	RpcErrorCode_BAD_REQUEST_CALL_ALREADY_ACCEPTED         RpcErrorCode = 4002029
	RpcErrorCode_BAD_REQUEST_CALL_ALREADY_DECLINED         RpcErrorCode = 4002030
	RpcErrorCode_BAD_REQUEST_CALL_PEER_INVALID             RpcErrorCode = 4002031
	RpcErrorCode_BAD_REQUEST_CALL_PROTOCOL_FLAGS_INVALID   RpcErrorCode = 4002032
	RpcErrorCode_BAD_REQUEST_USER_ADMIN_INVALID            RpcErrorCode = 4002034
	RpcErrorCode_BAD_REQUEST_CHAT_ADMIN_INVITE_REQUIRED    RpcErrorCode = 4002035
	RpcErrorCode_BAD_REQUEST_FRESH_CHANGE_ADMINS_FORBIDDEN RpcErrorCode = 4002036
	RpcErrorCode_BAD_REQUEST_RIGHT_FORBIDDEN               RpcErrorCode = 4002037
	RpcErrorCode_BAD_REQUEST_DATA_JSON_INVALID             RpcErrorCode = 4002041
	RpcErrorCode_BAD_REQUEST_INPUT_USER_DEACTIVATED        RpcErrorCode = 4002042
	RpcErrorCode_BAD_REQUEST_MEDIA_INVALID                 RpcErrorCode = 4002043
	RpcErrorCode_BAD_REQUEST_FILE_REFERENCE_EXPIRED        RpcErrorCode = 4002044
	//    400	CHAT_INVALID	Invalid chat
	//    400	CHAT_TITLE_EMPTY	No chat title provided
	//    400	INPUT_USER_DEACTIVATED	The specified user was deleted
	//    400	USERS_TOO_FEW	Not enough users (to create a chat, for example)
	//    403	USER_RESTRICTED	You're spamreported, you can't create channels or chats.
	RpcErrorCode_BAD_REQUEST_CHAT_INVALID     RpcErrorCode = 4002050
	RpcErrorCode_BAD_REQUEST_CHAT_TITLE_EMPTY RpcErrorCode = 4002051
	//    400	CHAT_ADMIN_REQUIRED	You must be an admin in this chat to do this.
	//    403	MESSAGE_AUTHOR_REQUIRED	Message author required.
	//    400	MESSAGE_ID_INVALID	The provided message id is invalid.
	//    400	PEER_ID_INVALID	The provided peer id is invalid.
	RpcErrorCode_BAD_REQUEST_MESSAGE_AUTHOR_REQUIRED RpcErrorCode = 4002052
	RpcErrorCode_BAD_REQUEST_MESSAGE_ID_INVALID      RpcErrorCode = 4002053
	//    400	BUTTON_DATA_INVALID	The data of one or more of the buttons you provided is invalid.
	//    400	BUTTON_TYPE_INVALID	The type of one or more of the buttons you provided is invalid.
	//    400	BUTTON_URL_INVALID	Button URL invalid.
	//    400	CHANNEL_INVALID	The provided channel is invalid.
	//    400	CHANNEL_PRIVATE	You haven't joined this channel/supergroup.
	//    403	CHAT_ADMIN_REQUIRED	You must be an admin in this chat to do this.
	//    403	CHAT_WRITE_FORBIDDEN	You can't write in this chat.
	//    400	ENTITIES_TOO_LONG	You provided too many styled message entities.
	//    403	INLINE_BOT_REQUIRED	Only the inline bot can edit message.
	//    400	INPUT_USER_DEACTIVATED	The specified user was deleted.
	//    400	MEDIA_CAPTION_TOO_LONG	The caption is too long.
	//    400	MEDIA_GROUPED_INVALID	You tried to send media of different types in an album.
	//    400	MEDIA_NEW_INVALID	The new media is invalid.
	//    400	MEDIA_PREV_INVALID	Previous media invalid.
	//    403	MESSAGE_AUTHOR_REQUIRED	Message author required.
	//    400	MESSAGE_EDIT_TIME_EXPIRED	You can't edit this message anymore, too much time has passed since its creation.
	//    400	MESSAGE_EMPTY	The provided message is empty.
	//    400	MESSAGE_ID_INVALID	The provided message id is invalid.
	//    400	MESSAGE_NOT_MODIFIED	The provided message data is identical to the previous message data, the message wasn't modified.
	//    400	MESSAGE_TOO_LONG	The provided message is too long.
	//    400	MSG_ID_INVALID	Invalid message ID provided.
	//    400	PEER_ID_INVALID	The provided peer id is invalid.
	//    400	REPLY_MARKUP_INVALID	The provided reply markup is invalid.
	//    400	SCHEDULE_DATE_INVALID	Invalid schedule date provided.
	//    400	USER_BANNED_IN_CHANNEL	You're banned from sending messages in supergroups/channels.
	RpcErrorCode_BAD_REQUEST_BUTTON_DATA_INVALID       RpcErrorCode = 4002054
	RpcErrorCode_BAD_REQUEST_BUTTON_TYPE_INVALID       RpcErrorCode = 4002055
	RpcErrorCode_BAD_REQUEST_BUTTON_URL_INVALID        RpcErrorCode = 4002056
	RpcErrorCode_BAD_REQUEST_ENTITIES_TOO_LONG         RpcErrorCode = 4002057
	RpcErrorCode_BAD_REQUEST_INLINE_BOT_REQUIRED       RpcErrorCode = 4002058
	RpcErrorCode_BAD_REQUEST_MESSAGE_NOT_MODIFIED      RpcErrorCode = 4002059
	RpcErrorCode_BAD_REQUEST_REPLY_MARKUP_INVALID      RpcErrorCode = 4002060
	RpcErrorCode_BAD_REQUEST_SCHEDULE_DATE_INVALID     RpcErrorCode = 4002061
	RpcErrorCode_BAD_REQUEST_MESSAGE_EDIT_TIME_EXPIRED RpcErrorCode = 4002062
	// 400 User not found
	RpcErrorCode_BAD_REQUEST_USER_NOT_FOUND             RpcErrorCode = 4002063
	RpcErrorCode_BAD_REQUEST_CHANNELS_TOO_MUCH          RpcErrorCode = 4002500
	RpcErrorCode_BAD_REQUEST_VIP_LIMIT                  RpcErrorCode = 4002505
	RpcErrorCode_BAD_REQUEST_PHOTO_ALBUM_NOT_FOUND      RpcErrorCode = 4002506
	RpcErrorCode_BAD_REQUEST_PHOTO_ALBUM_LIMIT          RpcErrorCode = 4002507
	RpcErrorCode_BAD_REQUEST_PHOTO_ALBUM_PINNED_LIMIT   RpcErrorCode = 4002508
	RpcErrorCode_BAD_REQUEST_PAYMENT_ORDER_ID_PAYMENTED RpcErrorCode = 4002700
	RpcErrorCode_BAD_REQUEST_PAYMENT_TRADE_NO_PAYMENTED RpcErrorCode = 4002701
	RpcErrorCode_BAD_REQUEST_PAYMENT_ORDER_ID_NOT_FOUND RpcErrorCode = 4002702
	//    401	AUTH_KEY_PERM_EMPTY	The temporary auth key must be binded to the permanent auth key to use these methods.
	//    400	BOT_DOMAIN_INVALID	Bot domain invalid
	//    400	BOT_INVALID	This is not a valid bot
	//    400	BUTTON_DATA_INVALID	The data of one or more of the buttons you provided is invalid
	//    400	BUTTON_TYPE_INVALID	The type of one or more of the buttons you provided is invalid
	//    400	BUTTON_URL_INVALID	Button URL invalid
	//    400	CHANNEL_INVALID	The provided channel is invalid
	//    400	CHANNEL_PRIVATE	You haven't joined this channel/supergroup
	//    400	CHAT_ADMIN_REQUIRED	You must be an admin in this chat to do this
	//    400	CHAT_ID_INVALID	The provided chat id is invalid
	//    400	CHAT_RESTRICTED	You can't send messages in this chat, you were restricted
	//    403	CHAT_WRITE_FORBIDDEN	You can't write in this chat
	//    400	ENCRYPTION_DECLINED	The secret chat was declined
	//    400	ENTITY_MENTION_USER_INVALID	You mentioned an invalid user
	//    400	FROM_MESSAGE_BOT_DISABLED	Bots can't use fromMessage min constructors
	//    400	INPUT_USER_DEACTIVATED	The specified user was deleted
	//    400	MESSAGE_EMPTY	The provided message is empty
	//    400	MESSAGE_TOO_LONG	The provided message is too long
	//    400	MSG_ID_INVALID	Provided reply_to_msg_id is invalid
	//    400	PEER_ID_INVALID	The provided peer id is invalid
	//    400	PINNED_DIALOGS_TOO_MUCH	Too many pinned dialogs
	//    400	REPLY_MARKUP_INVALID	The provided reply markup is invalid
	//    400	SCHEDULE_BOT_NOT_ALLOWED	Bots cannot schedule messages
	//    400	SCHEDULE_DATE_TOO_LATE	You can't schedule a message this far in the future
	//    400	SCHEDULE_TOO_MUCH	There are too many scheduled messages
	//    420	SLOWMODE_WAIT_X	Slowmode is enabled in this chat: you must wait for the specified number of seconds before sending another message to the chat.
	//    400	USER_BANNED_IN_CHANNEL	You're banned from sending messages in supergroups/channels
	//    400	USER_IS_BLOCKED	You were blocked by this user
	//    400	USER_IS_BOT	Bots can't send messages to other bots
	//    400	YOU_BLOCKED_USER	You blocked this user
	// 400	USER_ALREADY_PARTICIPANT	The user is already in the group
	// sendMessage
	RpcErrorCode_BAD_REQUEST_MESSAGE_EMPTY               RpcErrorCode = 4003001
	RpcErrorCode_BAD_REQUEST_MESSAGE_TOO_LONG            RpcErrorCode = 4003002
	RpcErrorCode_BAD_REQUEST_PINNED_DIALOGS_TOO_MUCH     RpcErrorCode = 4003003
	RpcErrorCode_BAD_REQUEST_USER_BANNED_IN_CHANNEL      RpcErrorCode = 4003004
	RpcErrorCode_BAD_REQUEST_USER_IS_BLOCKED             RpcErrorCode = 4003005
	RpcErrorCode_BAD_REQUEST_ENCRYPTION_DECLINED         RpcErrorCode = 4003006
	RpcErrorCode_BAD_REQUEST_CHAT_ID_INVALID             RpcErrorCode = 4003007
	RpcErrorCode_BAD_REQUEST_CHAT_WRITE_FORBIDDEN        RpcErrorCode = 4003008
	RpcErrorCode_BAD_REQUEST_INVITE_HASH_EMPTY           RpcErrorCode = 4003009
	RpcErrorCode_BAD_REQUEST_INVITE_HASH_INVALID         RpcErrorCode = 4003010
	RpcErrorCode_BAD_REQUEST_INVITE_HASH_EXPIRED         RpcErrorCode = 4003011
	RpcErrorCode_BAD_REQUEST_CHAT_RESTRICTED             RpcErrorCode = 4003012
	RpcErrorCode_BAD_REQUEST_USER_ALREADY_PARTICIPANT    RpcErrorCode = 4003013
	RpcErrorCode_BAD_REQUEST_CHANNEL_REMOVED_PARTICIPANT RpcErrorCode = 4003014
	RpcErrorCode_BAD_REQUEST_CHAT_NOT_MODIFIED           RpcErrorCode = 4003015
	RpcErrorCode_BAD_REQUEST_PIN_RESTRICTED              RpcErrorCode = 4003016
	//    Accepting a login token
	//    In order to log in, the QR code must be scanned and accepted by an already logged-in Telegram app using auth.acceptLoginToken.
	//    The token must be extracted from the tg://login URI and base64url-decoded before using it in the method.
	//
	//    Possible errors returned by the method are:
	//
	//    400 - AUTH_TOKEN_INVALID, an invalid authorization token was provided
	//        400 - AUTH_TOKEN_EXPIRED, the provided authorization token has expired and the updated QR-code must be re-scanned
	//        400 - AUTH_TOKEN_ALREADY_ACCEPTED, the authorization token was already used
	//    400	AUTH_TOKEN_ALREADY_ACCEPTED	The specified auth token was already accepted.
	//    400	AUTH_TOKEN_EXCEPTION	An error occurred while importing the auth token.
	//    400	AUTH_TOKEN_EXPIRED	The authorization token has expired.
	//    400	AUTH_TOKEN_INVALIDX	The specified auth token is invalid.
	RpcErrorCode_BAD_REQUEST_AUTH_TOKEN_INVALID          RpcErrorCode = 4007000
	RpcErrorCode_BAD_REQUEST_AUTH_TOKEN_EXPIRED          RpcErrorCode = 4007001
	RpcErrorCode_BAD_REQUEST_AUTH_TOKEN_ALREADY_ACCEPTED RpcErrorCode = 4007002
	RpcErrorCode_BAD_REQUEST_AUTH_TOKEN_EXCEPTION        RpcErrorCode = 4007003
	RpcErrorCode_BAD_REQUEST_AUTH_TOKEN_INVALIDX         RpcErrorCode = 4007004
	//    Code	Type	Description
	//    400	FILE_PART_EMPTY	The provided file part is empty
	//    400	FILE_PART_INVALID	The file part number is invalid
	//    400	FILE_PARTS_INVALID	The number of file parts is invalid
	//    400	FILE_PART_SIZE_CHANGED	Provided file part size has changed
	//    400	FILE_PART_SIZE_INVALID	The provided file part size is invalid
	//    400	FILE_PART_TOO_BIG	The uploaded file part is too big
	RpcErrorCode_BAD_UPLOAD                        RpcErrorCode = 4004000
	RpcErrorCode_BAD_UPLOAD_FILE_PART_EMPTY        RpcErrorCode = 4004001
	RpcErrorCode_BAD_UPLOAD_FILE_PART_INVALID      RpcErrorCode = 4004002
	RpcErrorCode_BAD_UPLOAD_FILE_PARTS_INVALID     RpcErrorCode = 4004003
	RpcErrorCode_BAD_UPLOAD_FILE_PART_SIZE_CHANGED RpcErrorCode = 4004004
	RpcErrorCode_BAD_UPLOAD_FILE_PART_SIZE_INVALID RpcErrorCode = 4004005
	RpcErrorCode_BAD_UPLOAD_FILE_PART_TOO_BIG      RpcErrorCode = 4004006
	RpcErrorCode_BAD_UPLOAD_FILE_LOCATION_INVALID  RpcErrorCode = 4004007
	//    400	FILE_REFERENCE_INVALID	The specified file reference is invalid.
	//    400	PHOTO_CROP_SIZE_SMALL	Photo is too small.
	//    400	PHOTO_EXT_INVALID	The extension of the photo is invalid.
	//    400	PHOTO_INVALID	Photo invalid.
	RpcErrorCode_BAD_UPLOAD_FILE_REFERENCE_INVALID RpcErrorCode = 4004008
	RpcErrorCode_BAD_UPLOAD_PHOTO_CROP_SIZE_SMALL  RpcErrorCode = 4004009
	RpcErrorCode_BAD_UPLOAD_FPHOTO_EXT_INVALID     RpcErrorCode = 4004010
	RpcErrorCode_BAD_UPLOAD_PHOTO_INVALID          RpcErrorCode = 4004011
	// bindTempAuthKey
	RpcErrorCode_BAD_REQUEST_ENCRYPTED_MESSAGE_INVALID   RpcErrorCode = 4002100
	RpcErrorCode_BAD_REQUEST_INPUT_REQUEST_TOO_LONG      RpcErrorCode = 4002200
	RpcErrorCode_BAD_REQUEST_TEMP_AUTH_KEY_ALREADY_BOUND RpcErrorCode = 4002300
	RpcErrorCode_BAD_REQUEST_TEMP_AUTH_KEY_EMPTY         RpcErrorCode = 4002400
	// langPackLanguage
	RpcErrorCode_BAD_REQUEST_LANG_PACK_INVALID          RpcErrorCode = 4003100
	RpcErrorCode_BAD_REQUEST_LANG_PACK_INVALID_LANGCODE RpcErrorCode = 4003101
	//    400	CALL_PROTOCOL_FLAGS_INVALID	Call protocol flags invalid
	//    400	PARTICIPANT_VERSION_OUTDATED	The other participant does not use an up to date telegram client with support for calls
	//    400	USER_ID_INVALID	The provided user ID is invalid
	//    403	USER_IS_BLOCKED	You were blocked by this user
	//    403	USER_PRIVACY_RESTRICTED	The user's privacy settings do not allow you to do this
	RpcErrorCode_BAD_REQUEST_PARTICIPANT_VERSION_OUTDATED RpcErrorCode = 4003120
	RpcErrorCode_BAD_REQUEST_USER_ID_INVALID              RpcErrorCode = 4003121
	RpcErrorCode_BAD_REQUEST_ABOUT_TOO_LONG               RpcErrorCode = 4005001
	RpcErrorCode_BAD_REQUEST_USER_NOT_MUTUAL_CONTACT      RpcErrorCode = 4005002
	// sticker sets
	RpcErrorCode_BAD_REQUEST_STICKER_ID_INVALID       RpcErrorCode = 4006000
	RpcErrorCode_BAD_REQUEST_STICKERSETS_FAVED_LIMIT  RpcErrorCode = 4006001
	RpcErrorCode_BAD_REQUEST_STICKERSETS_RECENT_LIMIT RpcErrorCode = 4006002
	//    401 UNAUTHORIZED
	//    There was an unauthorized attempt to use functionality available only to authorized users.
	//
	//    Examples of Errors:
	//    AUTH_KEY_UNREGISTERED: The key is not registered in the system
	//    AUTH_KEY_INVALID: The key is invalid
	//    USER_DEACTIVATED: The user has been deleted/deactivated
	//    SESSION_REVOKED: The authorization has been invalidated, because of the user terminating all sessions
	//    SESSION_EXPIRED: The authorization has expired
	//    AUTH_KEY_PERM_EMPTY: The method is unavailble for temporary authorization key, not bound to permanent
	RpcErrorCode_UNAUTHORIZED                         RpcErrorCode = 4010000
	RpcErrorCode_UNAUTHORIZED_AUTH_KEY_INVALID        RpcErrorCode = 4011000
	RpcErrorCode_UNAUTHORIZED_USER_DEACTIVATED        RpcErrorCode = 4012000
	RpcErrorCode_UNAUTHORIZED_SESSION_REVOKED         RpcErrorCode = 4013000
	RpcErrorCode_UNAUTHORIZED_SESSION_EXPIRED         RpcErrorCode = 4014000
	RpcErrorCode_UNAUTHORIZED_AUTH_KEY_PERM_EMPTY     RpcErrorCode = 4015000
	RpcErrorCode_UNAUTHORIZED_AUTH_KEY_UNREGISTERED   RpcErrorCode = 4015001
	RpcErrorCode_UNAUTHORIZED_SESSION_PASSWORD_NEEDED RpcErrorCode = 4015011
	//      403 FORBIDDEN
	//    Privacy violation. For example, an attempt to write a message to someone who has blacklisted the current user.
	//    403	USER_IS_BLOCKED	You were blocked by this user
	//    403	USER_PRIVACY_RESTRICTED	The user's privacy settings do not allow you to do this
	RpcErrorCode_FORBIDDEN                         RpcErrorCode = 4030000
	RpcErrorCode_FORBIDDEN_USER_IS_BLOCKED         RpcErrorCode = 4030002
	RpcErrorCode_FORBIDDEN_USER_PRIVACY_RESTRICTED RpcErrorCode = 4030003
	RpcErrorCode_FORBIDDEN_USER_RESTRICTED         RpcErrorCode = 4030004
	RpcErrorCode_FORBIDDEN_USER_NOT_MUTUAL_CONTACT RpcErrorCode = 4030005
	//  sendMessage
	RpcErrorCode_FORBIDDEN_DIRTY_WORD  RpcErrorCode = 4030001
	RpcErrorCode_FORBIDDEN_BLOCK_IMAGE RpcErrorCode = 4030006
	//  403	MESSAGE_DELETE_FORBIDDEN	You can't delete one of the messages you tried to delete, most likely because it is a service message.
	RpcErrorCode_FORBIDDEN_MESSAGE_DELETE_FORBIDDEN RpcErrorCode = 4030030
	//
	//  404 NOT_FOUND
	//    An attempt to invoke a non-existent object, such as a method.
	RpcErrorCode_NOT_FOUND RpcErrorCode = 4040000
	//
	//  406 NOT_ACCEPTABLE
	//    Similar to 400 BAD_REQUEST, but the app should not display any error messages to user in UI as a result of this response. The error message will be delivered via updateServiceNotification instead.
	//  406	FRESH_RESET_AUTHORISATION_FORBIDDEN	You can't logout other sessions if less than 24 hours have passed since you logged on the current session.
	RpcErrorCode_NOT_ACCEPTABLE                                     RpcErrorCode = 4060000
	RpcErrorCode_NOT_ACCEPTABLE_FRESH_RESET_AUTHORISATION_FORBIDDEN RpcErrorCode = 4060001
	//
	//  420 FLOOD
	//    The maximum allowed number of attempts to invoke the given method with the given input parameters has been exceeded. For example, in an attempt to request a large number of text messages (SMS) for the same phone number.
	//
	//    Error Example:
	//    FLOOD_WAIT_X: A wait of X seconds is required (where X is a number)
	RpcErrorCode_FLOOD                 RpcErrorCode = 4200000
	RpcErrorCode_FLOOD_WAIT            RpcErrorCode = 4201000
	RpcErrorCode_FLOOD_SLOWMODE_WAIT_X RpcErrorCode = 4201001
	//   HandShake error < 0
	//      other error code  reconnect
	RPCErrorCode_HANDSHAKE_PROXY          RpcErrorCode = -444
	RPCErrorCode_HANDSHAKE_RESET_AUTH_KEY RpcErrorCode = -404
	//    500 INTERNAL
	//    An internal server error occurred while a request was being processed; for example, there was a disruption while accessing a database or file storage.
	//
	//    If a client receives a 500 error, or you believe this error should not have occurred, please collect as much information as possible about the query and error and send it to the developers.
	RpcErrorCode_INTERNAL                   RpcErrorCode = 5000000
	RpcErrorCode_INTERNAL_RPC_RETURN_PARAMS RpcErrorCode = 5001000
)

var RpcErrorCode_name = map[int32]string{
	0:       "RpcErrorCode_OK",
	10000:   "RpcErrorCode_BASE_NUMBER",
	10001:   "RpcErrorCode_UNKNOWN",
	10002:   "RpcErrorCode_ErrorFormatUNKNOWN",
	10003:   "RpcErrorCode_TIMEOUT",
	3030000: "RpcErrorCode_SEE_OTHER",
	3031000: "RpcErrorCode_SEE_OTHER_FILE_MIGRATE",
	3032000: "RpcErrorCode_SEE_OTHER_PHONE_MIGRATE",
	3033000: "RpcErrorCode_SEE_OTHER_NETWORK_MIGRATE",
	3034000: "RpcErrorCode_SEE_OTHER_USER_MIGRATE",
	3034001: "RpcErrorCode_SEE_OTHER_X_MAX",
	4000000: "RpcErrorCode_BAD_REQUEST",
	4000100: "RpcErrorCode_BAD_REQUEST_FIRSTNAME_INVALID",
	4000200: "RpcErrorCode_BAD_REQUEST_LASTNAME_INVALID",
	4000300: "RpcErrorCode_BAD_REQUEST_PHONE_NUMBER_INVALID",
	4000400: "RpcErrorCode_BAD_REQUEST_PHONE_CODE_HASH_EMPTY",
	4000500: "RpcErrorCode_BAD_REQUEST_PHONE_CODE_EMPTY",
	4000501: "RpcErrorCode_BAD_REQUEST_PHONE_CODE_INVALID",
	4000600: "RpcErrorCode_BAD_REQUEST_PHONE_CODE_EXPIRED",
	4000700: "RpcErrorCode_BAD_REQUEST_API_ID_INVALID",
	4000800: "RpcErrorCode_BAD_REQUEST_PHONE_NUMBER_OCCUPIED",
	4000900: "RpcErrorCode_BAD_REQUEST_PHONE_NUMBER_UNOCCUPIED",
	4001000: "RpcErrorCode_BAD_REQUEST_USERS_TOO_FEW",
	4001100: "RpcErrorCode_BAD_REQUEST_USERS_TOO_MUCH",
	4001200: "RpcErrorCode_BAD_REQUEST_TYPE_CONSTRUCTOR_INVALID",
	4001300: "RpcErrorCode_BAD_REQUEST_FILE_PART_INVALID",
	4001400: "RpcErrorCode_BAD_REQUEST_FILE_PARTS_INVALID",
	4001500: "RpcErrorCode_BAD_REQUEST_FILE_PART_X_MISSING",
	4001600: "RpcErrorCode_BAD_REQUEST_MD5_CHECKSUM_INVALID",
	4001700: "RpcErrorCode_BAD_REQUEST_PHOTO_INVALID_DIMENSIONS",
	4001800: "RpcErrorCode_BAD_REQUEST_FIELD_NAME_INVALID",
	4001900: "RpcErrorCode_BAD_REQUEST_FIELD_NAME_EMPTY",
	4002000: "RpcErrorCode_BAD_REQUEST_MSG_WAIT_FAILED",
	4002001: "RpcErrorCode_BAD_REQUEST_PHONE_NUMBER_BANNED",
	4002002: "RpcErrorCode_BAD_REQUEST_PHONE_NUMBER_FLOOD",
	4002003: "RpcErrorCode_BAD_REQUEST_PHONE_PASSWORD_FLOOD",
	4002004: "RpcErrorCode_BAD_REQUEST_PHONE_PASSWORD_PROTECTED",
	4002005: "RpcErrorCode_BAD_REQUEST_AUTH_KEY_PERM_EMPTY",
	4002006: "RpcErrorCode_BAD_REQUEST_API_ID_PUBLISHED_FLOOD",
	4002007: "RpcErrorCode_BAD_REQUEST_PHONE_NUMBER_APP_SIGNUP_FORBIDDEN",
	4002008: "RpcErrorCode_BAD_REQUEST_INPUT_CONSTRUCTOR_INVALID",
	4002009: "RpcErrorCode_BAD_REQUEST_PEER_ID_INVALID",
	4002010: "RpcErrorCode_BAD_REQUEST_TOKEN_INVALID",
	4002011: "RpcErrorCode_BAD_REQUEST_NO_PROMISSION",
	4002012: "RpcErrorCode_BAD_REQUEST_STICKERSET_INVALID",
	4002013: "RpcErrorCode_BAD_REQUEST_CONTACT_ID_INVALID",
	4002014: "RpcErrorCode_BAD_REQUEST_CONTACT_NAME_EMPTY",
	4002015: "RpcErrorCode_BAD_REQUEST_MSG_ID_INVALID",
	4002016: "RpcErrorCode_BAD_REQUEST_CDN_METHOD_INVALID",
	4002017: "RpcErrorCode_BAD_REQUEST_DATE_EMPTY",
	4002018: "RpcErrorCode_BAD_REQUEST_PERSISTENT_TIMESTAMP_EMPTY",
	4002019: "RpcErrorCode_BAD_REQUEST_PERSISTENT_TIMESTAMP_INVALID",
	4002020: "RpcErrorCode_BAD_REQUEST_QUERY_TOO_SHORT",
	4002021: "RpcErrorCode_BAD_REQUEST_SEARCH_QUERY_EMPTY",
	4002022: "RpcErrorCode_BAD_REQUEST_USERNAME_INVALID",
	4002023: "RpcErrorCode_BAD_REQUEST_USERNAME_OCCUPIED",
	4002024: "RpcErrorCode_BAD_REQUEST_USERNAME_NOT_MODIFIED",
	4002025: "RpcErrorCode_BAD_REQUEST_CHANNEL_INVALID",
	4002026: "RpcErrorCode_BAD_REQUEST_CHANNEL_PRIVATE",
	4002027: "RpcErrorCode_BAD_REQUEST_CHAT_ADMIN_REQUIRED",
	4002028: "RpcErrorCode_BAD_REQUEST_PEER_ID_NOT_SUPPORTED",
	4002029: "RpcErrorCode_BAD_REQUEST_CALL_ALREADY_ACCEPTED",
	4002030: "RpcErrorCode_BAD_REQUEST_CALL_ALREADY_DECLINED",
	4002031: "RpcErrorCode_BAD_REQUEST_CALL_PEER_INVALID",
	4002032: "RpcErrorCode_BAD_REQUEST_CALL_PROTOCOL_FLAGS_INVALID",
	4002034: "RpcErrorCode_BAD_REQUEST_USER_ADMIN_INVALID",
	4002035: "RpcErrorCode_BAD_REQUEST_CHAT_ADMIN_INVITE_REQUIRED",
	4002036: "RpcErrorCode_BAD_REQUEST_FRESH_CHANGE_ADMINS_FORBIDDEN",
	4002037: "RpcErrorCode_BAD_REQUEST_RIGHT_FORBIDDEN",
	4002041: "RpcErrorCode_BAD_REQUEST_DATA_JSON_INVALID",
	4002042: "RpcErrorCode_BAD_REQUEST_INPUT_USER_DEACTIVATED",
	4002043: "RpcErrorCode_BAD_REQUEST_MEDIA_INVALID",
	4002044: "RpcErrorCode_BAD_REQUEST_FILE_REFERENCE_EXPIRED",
	4002050: "RpcErrorCode_BAD_REQUEST_CHAT_INVALID",
	4002051: "RpcErrorCode_BAD_REQUEST_CHAT_TITLE_EMPTY",
	4002052: "RpcErrorCode_BAD_REQUEST_MESSAGE_AUTHOR_REQUIRED",
	4002053: "RpcErrorCode_BAD_REQUEST_MESSAGE_ID_INVALID",
	4002054: "RpcErrorCode_BAD_REQUEST_BUTTON_DATA_INVALID",
	4002055: "RpcErrorCode_BAD_REQUEST_BUTTON_TYPE_INVALID",
	4002056: "RpcErrorCode_BAD_REQUEST_BUTTON_URL_INVALID",
	4002057: "RpcErrorCode_BAD_REQUEST_ENTITIES_TOO_LONG",
	4002058: "RpcErrorCode_BAD_REQUEST_INLINE_BOT_REQUIRED",
	4002059: "RpcErrorCode_BAD_REQUEST_MESSAGE_NOT_MODIFIED",
	4002060: "RpcErrorCode_BAD_REQUEST_REPLY_MARKUP_INVALID",
	4002061: "RpcErrorCode_BAD_REQUEST_SCHEDULE_DATE_INVALID",
	4002062: "RpcErrorCode_BAD_REQUEST_MESSAGE_EDIT_TIME_EXPIRED",
	4002063: "RpcErrorCode_BAD_REQUEST_USER_NOT_FOUND",
	4002500: "RpcErrorCode_BAD_REQUEST_CHANNELS_TOO_MUCH",
	4002505: "RpcErrorCode_BAD_REQUEST_VIP_LIMIT",
	4002506: "RpcErrorCode_BAD_REQUEST_PHOTO_ALBUM_NOT_FOUND",
	4002507: "RpcErrorCode_BAD_REQUEST_PHOTO_ALBUM_LIMIT",
	4002508: "RpcErrorCode_BAD_REQUEST_PHOTO_ALBUM_PINNED_LIMIT",
	4002700: "RpcErrorCode_BAD_REQUEST_PAYMENT_ORDER_ID_PAYMENTED",
	4002701: "RpcErrorCode_BAD_REQUEST_PAYMENT_TRADE_NO_PAYMENTED",
	4002702: "RpcErrorCode_BAD_REQUEST_PAYMENT_ORDER_ID_NOT_FOUND",
	4003001: "RpcErrorCode_BAD_REQUEST_MESSAGE_EMPTY",
	4003002: "RpcErrorCode_BAD_REQUEST_MESSAGE_TOO_LONG",
	4003003: "RpcErrorCode_BAD_REQUEST_PINNED_DIALOGS_TOO_MUCH",
	4003004: "RpcErrorCode_BAD_REQUEST_USER_BANNED_IN_CHANNEL",
	4003005: "RpcErrorCode_BAD_REQUEST_USER_IS_BLOCKED",
	4003006: "RpcErrorCode_BAD_REQUEST_ENCRYPTION_DECLINED",
	4003007: "RpcErrorCode_BAD_REQUEST_CHAT_ID_INVALID",
	4003008: "RpcErrorCode_BAD_REQUEST_CHAT_WRITE_FORBIDDEN",
	4003009: "RpcErrorCode_BAD_REQUEST_INVITE_HASH_EMPTY",
	4003010: "RpcErrorCode_BAD_REQUEST_INVITE_HASH_INVALID",
	4003011: "RpcErrorCode_BAD_REQUEST_INVITE_HASH_EXPIRED",
	4003012: "RpcErrorCode_BAD_REQUEST_CHAT_RESTRICTED",
	4003013: "RpcErrorCode_BAD_REQUEST_USER_ALREADY_PARTICIPANT",
	4003014: "RpcErrorCode_BAD_REQUEST_CHANNEL_REMOVED_PARTICIPANT",
	4003015: "RpcErrorCode_BAD_REQUEST_CHAT_NOT_MODIFIED",
	4003016: "RpcErrorCode_BAD_REQUEST_PIN_RESTRICTED",
	4007000: "RpcErrorCode_BAD_REQUEST_AUTH_TOKEN_INVALID",
	4007001: "RpcErrorCode_BAD_REQUEST_AUTH_TOKEN_EXPIRED",
	4007002: "RpcErrorCode_BAD_REQUEST_AUTH_TOKEN_ALREADY_ACCEPTED",
	4007003: "RpcErrorCode_BAD_REQUEST_AUTH_TOKEN_EXCEPTION",
	4007004: "RpcErrorCode_BAD_REQUEST_AUTH_TOKEN_INVALIDX",
	4004000: "RpcErrorCode_BAD_UPLOAD",
	4004001: "RpcErrorCode_BAD_UPLOAD_FILE_PART_EMPTY",
	4004002: "RpcErrorCode_BAD_UPLOAD_FILE_PART_INVALID",
	4004003: "RpcErrorCode_BAD_UPLOAD_FILE_PARTS_INVALID",
	4004004: "RpcErrorCode_BAD_UPLOAD_FILE_PART_SIZE_CHANGED",
	4004005: "RpcErrorCode_BAD_UPLOAD_FILE_PART_SIZE_INVALID",
	4004006: "RpcErrorCode_BAD_UPLOAD_FILE_PART_TOO_BIG",
	4004007: "RpcErrorCode_BAD_UPLOAD_FILE_LOCATION_INVALID",
	4004008: "RpcErrorCode_BAD_UPLOAD_FILE_REFERENCE_INVALID",
	4004009: "RpcErrorCode_BAD_UPLOAD_PHOTO_CROP_SIZE_SMALL",
	4004010: "RpcErrorCode_BAD_UPLOAD_FPHOTO_EXT_INVALID",
	4004011: "RpcErrorCode_BAD_UPLOAD_PHOTO_INVALID",
	4002100: "RpcErrorCode_BAD_REQUEST_ENCRYPTED_MESSAGE_INVALID",
	4002200: "RpcErrorCode_BAD_REQUEST_INPUT_REQUEST_TOO_LONG",
	4002300: "RpcErrorCode_BAD_REQUEST_TEMP_AUTH_KEY_ALREADY_BOUND",
	4002400: "RpcErrorCode_BAD_REQUEST_TEMP_AUTH_KEY_EMPTY",
	4003100: "RpcErrorCode_BAD_REQUEST_LANG_PACK_INVALID",
	4003101: "RpcErrorCode_BAD_REQUEST_LANG_PACK_INVALID_LANGCODE",
	4003120: "RpcErrorCode_BAD_REQUEST_PARTICIPANT_VERSION_OUTDATED",
	4003121: "RpcErrorCode_BAD_REQUEST_USER_ID_INVALID",
	4005001: "RpcErrorCode_BAD_REQUEST_ABOUT_TOO_LONG",
	4005002: "RpcErrorCode_BAD_REQUEST_USER_NOT_MUTUAL_CONTACT",
	4006000: "RpcErrorCode_BAD_REQUEST_STICKER_ID_INVALID",
	4006001: "RpcErrorCode_BAD_REQUEST_STICKERSETS_FAVED_LIMIT",
	4006002: "RpcErrorCode_BAD_REQUEST_STICKERSETS_RECENT_LIMIT",
	4010000: "RpcErrorCode_UNAUTHORIZED",
	4011000: "RpcErrorCode_UNAUTHORIZED_AUTH_KEY_INVALID",
	4012000: "RpcErrorCode_UNAUTHORIZED_USER_DEACTIVATED",
	4013000: "RpcErrorCode_UNAUTHORIZED_SESSION_REVOKED",
	4014000: "RpcErrorCode_UNAUTHORIZED_SESSION_EXPIRED",
	4015000: "RpcErrorCode_UNAUTHORIZED_AUTH_KEY_PERM_EMPTY",
	4015001: "RpcErrorCode_UNAUTHORIZED_AUTH_KEY_UNREGISTERED",
	4015011: "RpcErrorCode_UNAUTHORIZED_SESSION_PASSWORD_NEEDED",
	4030000: "RpcErrorCode_FORBIDDEN",
	4030002: "RpcErrorCode_FORBIDDEN_USER_IS_BLOCKED",
	4030003: "RpcErrorCode_FORBIDDEN_USER_PRIVACY_RESTRICTED",
	4030004: "RpcErrorCode_FORBIDDEN_USER_RESTRICTED",
	4030005: "RpcErrorCode_FORBIDDEN_USER_NOT_MUTUAL_CONTACT",
	4030001: "RpcErrorCode_FORBIDDEN_DIRTY_WORD",
	4030006: "RpcErrorCode_FORBIDDEN_BLOCK_IMAGE",
	4030030: "RpcErrorCode_FORBIDDEN_MESSAGE_DELETE_FORBIDDEN",
	4040000: "RpcErrorCode_NOT_FOUND",
	4060000: "RpcErrorCode_NOT_ACCEPTABLE",
	4060001: "RpcErrorCode_NOT_ACCEPTABLE_FRESH_RESET_AUTHORISATION_FORBIDDEN",
	4200000: "RpcErrorCode_FLOOD",
	4201000: "RpcErrorCode_FLOOD_WAIT",
	4201001: "RpcErrorCode_FLOOD_SLOWMODE_WAIT_X",
	-444:    "RPCErrorCode_HANDSHAKE_PROXY",
	-404:    "RPCErrorCode_HANDSHAKE_RESET_AUTH_KEY",
	5000000: "RpcErrorCode_INTERNAL",
	5001000: "RpcErrorCode_INTERNAL_RPC_RETURN_PARAMS",
}

var RpcErrorCode_value = map[string]int32{
	"RpcErrorCode_OK":                                                 0,
	"RpcErrorCode_BASE_NUMBER":                                        10000,
	"RpcErrorCode_UNKNOWN":                                            10001,
	"RpcErrorCode_ErrorFormatUNKNOWN":                                 10002,
	"RpcErrorCode_TIMEOUT":                                            10003,
	"RpcErrorCode_SEE_OTHER":                                          3030000,
	"RpcErrorCode_SEE_OTHER_FILE_MIGRATE":                             3031000,
	"RpcErrorCode_SEE_OTHER_PHONE_MIGRATE":                            3032000,
	"RpcErrorCode_SEE_OTHER_NETWORK_MIGRATE":                          3033000,
	"RpcErrorCode_SEE_OTHER_USER_MIGRATE":                             3034000,
	"RpcErrorCode_SEE_OTHER_X_MAX":                                    3034001,
	"RpcErrorCode_BAD_REQUEST":                                        4000000,
	"RpcErrorCode_BAD_REQUEST_FIRSTNAME_INVALID":                      4000100,
	"RpcErrorCode_BAD_REQUEST_LASTNAME_INVALID":                       4000200,
	"RpcErrorCode_BAD_REQUEST_PHONE_NUMBER_INVALID":                   4000300,
	"RpcErrorCode_BAD_REQUEST_PHONE_CODE_HASH_EMPTY":                  4000400,
	"RpcErrorCode_BAD_REQUEST_PHONE_CODE_EMPTY":                       4000500,
	"RpcErrorCode_BAD_REQUEST_PHONE_CODE_INVALID":                     4000501,
	"RpcErrorCode_BAD_REQUEST_PHONE_CODE_EXPIRED":                     4000600,
	"RpcErrorCode_BAD_REQUEST_API_ID_INVALID":                         4000700,
	"RpcErrorCode_BAD_REQUEST_PHONE_NUMBER_OCCUPIED":                  4000800,
	"RpcErrorCode_BAD_REQUEST_PHONE_NUMBER_UNOCCUPIED":                4000900,
	"RpcErrorCode_BAD_REQUEST_USERS_TOO_FEW":                          4001000,
	"RpcErrorCode_BAD_REQUEST_USERS_TOO_MUCH":                         4001100,
	"RpcErrorCode_BAD_REQUEST_TYPE_CONSTRUCTOR_INVALID":               4001200,
	"RpcErrorCode_BAD_REQUEST_FILE_PART_INVALID":                      4001300,
	"RpcErrorCode_BAD_REQUEST_FILE_PARTS_INVALID":                     4001400,
	"RpcErrorCode_BAD_REQUEST_FILE_PART_X_MISSING":                    4001500,
	"RpcErrorCode_BAD_REQUEST_MD5_CHECKSUM_INVALID":                   4001600,
	"RpcErrorCode_BAD_REQUEST_PHOTO_INVALID_DIMENSIONS":               4001700,
	"RpcErrorCode_BAD_REQUEST_FIELD_NAME_INVALID":                     4001800,
	"RpcErrorCode_BAD_REQUEST_FIELD_NAME_EMPTY":                       4001900,
	"RpcErrorCode_BAD_REQUEST_MSG_WAIT_FAILED":                        4002000,
	"RpcErrorCode_BAD_REQUEST_PHONE_NUMBER_BANNED":                    4002001,
	"RpcErrorCode_BAD_REQUEST_PHONE_NUMBER_FLOOD":                     4002002,
	"RpcErrorCode_BAD_REQUEST_PHONE_PASSWORD_FLOOD":                   4002003,
	"RpcErrorCode_BAD_REQUEST_PHONE_PASSWORD_PROTECTED":               4002004,
	"RpcErrorCode_BAD_REQUEST_AUTH_KEY_PERM_EMPTY":                    4002005,
	"RpcErrorCode_BAD_REQUEST_API_ID_PUBLISHED_FLOOD":                 4002006,
	"RpcErrorCode_BAD_REQUEST_PHONE_NUMBER_APP_SIGNUP_FORBIDDEN":      4002007,
	"RpcErrorCode_BAD_REQUEST_INPUT_CONSTRUCTOR_INVALID":              4002008,
	"RpcErrorCode_BAD_REQUEST_PEER_ID_INVALID":                        4002009,
	"RpcErrorCode_BAD_REQUEST_TOKEN_INVALID":                          4002010,
	"RpcErrorCode_BAD_REQUEST_NO_PROMISSION":                          4002011,
	"RpcErrorCode_BAD_REQUEST_STICKERSET_INVALID":                     4002012,
	"RpcErrorCode_BAD_REQUEST_CONTACT_ID_INVALID":                     4002013,
	"RpcErrorCode_BAD_REQUEST_CONTACT_NAME_EMPTY":                     4002014,
	"RpcErrorCode_BAD_REQUEST_MSG_ID_INVALID":                         4002015,
	"RpcErrorCode_BAD_REQUEST_CDN_METHOD_INVALID":                     4002016,
	"RpcErrorCode_BAD_REQUEST_DATE_EMPTY":                             4002017,
	"RpcErrorCode_BAD_REQUEST_PERSISTENT_TIMESTAMP_EMPTY":             4002018,
	"RpcErrorCode_BAD_REQUEST_PERSISTENT_TIMESTAMP_INVALID":           4002019,
	"RpcErrorCode_BAD_REQUEST_QUERY_TOO_SHORT":                        4002020,
	"RpcErrorCode_BAD_REQUEST_SEARCH_QUERY_EMPTY":                     4002021,
	"RpcErrorCode_BAD_REQUEST_USERNAME_INVALID":                       4002022,
	"RpcErrorCode_BAD_REQUEST_USERNAME_OCCUPIED":                      4002023,
	"RpcErrorCode_BAD_REQUEST_USERNAME_NOT_MODIFIED":                  4002024,
	"RpcErrorCode_BAD_REQUEST_CHANNEL_INVALID":                        4002025,
	"RpcErrorCode_BAD_REQUEST_CHANNEL_PRIVATE":                        4002026,
	"RpcErrorCode_BAD_REQUEST_CHAT_ADMIN_REQUIRED":                    4002027,
	"RpcErrorCode_BAD_REQUEST_PEER_ID_NOT_SUPPORTED":                  4002028,
	"RpcErrorCode_BAD_REQUEST_CALL_ALREADY_ACCEPTED":                  4002029,
	"RpcErrorCode_BAD_REQUEST_CALL_ALREADY_DECLINED":                  4002030,
	"RpcErrorCode_BAD_REQUEST_CALL_PEER_INVALID":                      4002031,
	"RpcErrorCode_BAD_REQUEST_CALL_PROTOCOL_FLAGS_INVALID":            4002032,
	"RpcErrorCode_BAD_REQUEST_USER_ADMIN_INVALID":                     4002034,
	"RpcErrorCode_BAD_REQUEST_CHAT_ADMIN_INVITE_REQUIRED":             4002035,
	"RpcErrorCode_BAD_REQUEST_FRESH_CHANGE_ADMINS_FORBIDDEN":          4002036,
	"RpcErrorCode_BAD_REQUEST_RIGHT_FORBIDDEN":                        4002037,
	"RpcErrorCode_BAD_REQUEST_DATA_JSON_INVALID":                      4002041,
	"RpcErrorCode_BAD_REQUEST_INPUT_USER_DEACTIVATED":                 4002042,
	"RpcErrorCode_BAD_REQUEST_MEDIA_INVALID":                          4002043,
	"RpcErrorCode_BAD_REQUEST_FILE_REFERENCE_EXPIRED":                 4002044,
	"RpcErrorCode_BAD_REQUEST_CHAT_INVALID":                           4002050,
	"RpcErrorCode_BAD_REQUEST_CHAT_TITLE_EMPTY":                       4002051,
	"RpcErrorCode_BAD_REQUEST_MESSAGE_AUTHOR_REQUIRED":                4002052,
	"RpcErrorCode_BAD_REQUEST_MESSAGE_ID_INVALID":                     4002053,
	"RpcErrorCode_BAD_REQUEST_BUTTON_DATA_INVALID":                    4002054,
	"RpcErrorCode_BAD_REQUEST_BUTTON_TYPE_INVALID":                    4002055,
	"RpcErrorCode_BAD_REQUEST_BUTTON_URL_INVALID":                     4002056,
	"RpcErrorCode_BAD_REQUEST_ENTITIES_TOO_LONG":                      4002057,
	"RpcErrorCode_BAD_REQUEST_INLINE_BOT_REQUIRED":                    4002058,
	"RpcErrorCode_BAD_REQUEST_MESSAGE_NOT_MODIFIED":                   4002059,
	"RpcErrorCode_BAD_REQUEST_REPLY_MARKUP_INVALID":                   4002060,
	"RpcErrorCode_BAD_REQUEST_SCHEDULE_DATE_INVALID":                  4002061,
	"RpcErrorCode_BAD_REQUEST_MESSAGE_EDIT_TIME_EXPIRED":              4002062,
	"RpcErrorCode_BAD_REQUEST_USER_NOT_FOUND":                         4002063,
	"RpcErrorCode_BAD_REQUEST_CHANNELS_TOO_MUCH":                      4002500,
	"RpcErrorCode_BAD_REQUEST_VIP_LIMIT":                              4002505,
	"RpcErrorCode_BAD_REQUEST_PHOTO_ALBUM_NOT_FOUND":                  4002506,
	"RpcErrorCode_BAD_REQUEST_PHOTO_ALBUM_LIMIT":                      4002507,
	"RpcErrorCode_BAD_REQUEST_PHOTO_ALBUM_PINNED_LIMIT":               4002508,
	"RpcErrorCode_BAD_REQUEST_PAYMENT_ORDER_ID_PAYMENTED":             4002700,
	"RpcErrorCode_BAD_REQUEST_PAYMENT_TRADE_NO_PAYMENTED":             4002701,
	"RpcErrorCode_BAD_REQUEST_PAYMENT_ORDER_ID_NOT_FOUND":             4002702,
	"RpcErrorCode_BAD_REQUEST_MESSAGE_EMPTY":                          4003001,
	"RpcErrorCode_BAD_REQUEST_MESSAGE_TOO_LONG":                       4003002,
	"RpcErrorCode_BAD_REQUEST_PINNED_DIALOGS_TOO_MUCH":                4003003,
	"RpcErrorCode_BAD_REQUEST_USER_BANNED_IN_CHANNEL":                 4003004,
	"RpcErrorCode_BAD_REQUEST_USER_IS_BLOCKED":                        4003005,
	"RpcErrorCode_BAD_REQUEST_ENCRYPTION_DECLINED":                    4003006,
	"RpcErrorCode_BAD_REQUEST_CHAT_ID_INVALID":                        4003007,
	"RpcErrorCode_BAD_REQUEST_CHAT_WRITE_FORBIDDEN":                   4003008,
	"RpcErrorCode_BAD_REQUEST_INVITE_HASH_EMPTY":                      4003009,
	"RpcErrorCode_BAD_REQUEST_INVITE_HASH_INVALID":                    4003010,
	"RpcErrorCode_BAD_REQUEST_INVITE_HASH_EXPIRED":                    4003011,
	"RpcErrorCode_BAD_REQUEST_CHAT_RESTRICTED":                        4003012,
	"RpcErrorCode_BAD_REQUEST_USER_ALREADY_PARTICIPANT":               4003013,
	"RpcErrorCode_BAD_REQUEST_CHANNEL_REMOVED_PARTICIPANT":            4003014,
	"RpcErrorCode_BAD_REQUEST_CHAT_NOT_MODIFIED":                      4003015,
	"RpcErrorCode_BAD_REQUEST_PIN_RESTRICTED":                         4003016,
	"RpcErrorCode_BAD_REQUEST_AUTH_TOKEN_INVALID":                     4007000,
	"RpcErrorCode_BAD_REQUEST_AUTH_TOKEN_EXPIRED":                     4007001,
	"RpcErrorCode_BAD_REQUEST_AUTH_TOKEN_ALREADY_ACCEPTED":            4007002,
	"RpcErrorCode_BAD_REQUEST_AUTH_TOKEN_EXCEPTION":                   4007003,
	"RpcErrorCode_BAD_REQUEST_AUTH_TOKEN_INVALIDX":                    4007004,
	"RpcErrorCode_BAD_UPLOAD":                                         4004000,
	"RpcErrorCode_BAD_UPLOAD_FILE_PART_EMPTY":                         4004001,
	"RpcErrorCode_BAD_UPLOAD_FILE_PART_INVALID":                       4004002,
	"RpcErrorCode_BAD_UPLOAD_FILE_PARTS_INVALID":                      4004003,
	"RpcErrorCode_BAD_UPLOAD_FILE_PART_SIZE_CHANGED":                  4004004,
	"RpcErrorCode_BAD_UPLOAD_FILE_PART_SIZE_INVALID":                  4004005,
	"RpcErrorCode_BAD_UPLOAD_FILE_PART_TOO_BIG":                       4004006,
	"RpcErrorCode_BAD_UPLOAD_FILE_LOCATION_INVALID":                   4004007,
	"RpcErrorCode_BAD_UPLOAD_FILE_REFERENCE_INVALID":                  4004008,
	"RpcErrorCode_BAD_UPLOAD_PHOTO_CROP_SIZE_SMALL":                   4004009,
	"RpcErrorCode_BAD_UPLOAD_FPHOTO_EXT_INVALID":                      4004010,
	"RpcErrorCode_BAD_UPLOAD_PHOTO_INVALID":                           4004011,
	"RpcErrorCode_BAD_REQUEST_ENCRYPTED_MESSAGE_INVALID":              4002100,
	"RpcErrorCode_BAD_REQUEST_INPUT_REQUEST_TOO_LONG":                 4002200,
	"RpcErrorCode_BAD_REQUEST_TEMP_AUTH_KEY_ALREADY_BOUND":            4002300,
	"RpcErrorCode_BAD_REQUEST_TEMP_AUTH_KEY_EMPTY":                    4002400,
	"RpcErrorCode_BAD_REQUEST_LANG_PACK_INVALID":                      4003100,
	"RpcErrorCode_BAD_REQUEST_LANG_PACK_INVALID_LANGCODE":             4003101,
	"RpcErrorCode_BAD_REQUEST_PARTICIPANT_VERSION_OUTDATED":           4003120,
	"RpcErrorCode_BAD_REQUEST_USER_ID_INVALID":                        4003121,
	"RpcErrorCode_BAD_REQUEST_ABOUT_TOO_LONG":                         4005001,
	"RpcErrorCode_BAD_REQUEST_USER_NOT_MUTUAL_CONTACT":                4005002,
	"RpcErrorCode_BAD_REQUEST_STICKER_ID_INVALID":                     4006000,
	"RpcErrorCode_BAD_REQUEST_STICKERSETS_FAVED_LIMIT":                4006001,
	"RpcErrorCode_BAD_REQUEST_STICKERSETS_RECENT_LIMIT":               4006002,
	"RpcErrorCode_UNAUTHORIZED":                                       4010000,
	"RpcErrorCode_UNAUTHORIZED_AUTH_KEY_INVALID":                      4011000,
	"RpcErrorCode_UNAUTHORIZED_USER_DEACTIVATED":                      4012000,
	"RpcErrorCode_UNAUTHORIZED_SESSION_REVOKED":                       4013000,
	"RpcErrorCode_UNAUTHORIZED_SESSION_EXPIRED":                       4014000,
	"RpcErrorCode_UNAUTHORIZED_AUTH_KEY_PERM_EMPTY":                   4015000,
	"RpcErrorCode_UNAUTHORIZED_AUTH_KEY_UNREGISTERED":                 4015001,
	"RpcErrorCode_UNAUTHORIZED_SESSION_PASSWORD_NEEDED":               4015011,
	"RpcErrorCode_FORBIDDEN":                                          4030000,
	"RpcErrorCode_FORBIDDEN_USER_IS_BLOCKED":                          4030002,
	"RpcErrorCode_FORBIDDEN_USER_PRIVACY_RESTRICTED":                  4030003,
	"RpcErrorCode_FORBIDDEN_USER_RESTRICTED":                          4030004,
	"RpcErrorCode_FORBIDDEN_USER_NOT_MUTUAL_CONTACT":                  4030005,
	"RpcErrorCode_FORBIDDEN_DIRTY_WORD":                               4030001,
	"RpcErrorCode_FORBIDDEN_BLOCK_IMAGE":                              4030006,
	"RpcErrorCode_FORBIDDEN_MESSAGE_DELETE_FORBIDDEN":                 4030030,
	"RpcErrorCode_NOT_FOUND":                                          4040000,
	"RpcErrorCode_NOT_ACCEPTABLE":                                     4060000,
	"RpcErrorCode_NOT_ACCEPTABLE_FRESH_RESET_AUTHORISATION_FORBIDDEN": 4060001,
	"RpcErrorCode_FLOOD":                                              4200000,
	"RpcErrorCode_FLOOD_WAIT":                                         4201000,
	"RpcErrorCode_FLOOD_SLOWMODE_WAIT_X":                              4201001,
	"RPCErrorCode_HANDSHAKE_PROXY":                                    -444,
	"RPCErrorCode_HANDSHAKE_RESET_AUTH_KEY":                           -404,
	"RpcErrorCode_INTERNAL":                                           5000000,
	"RpcErrorCode_INTERNAL_RPC_RETURN_PARAMS":                         5001000,
}

func (x RpcErrorCode) String() string {
	return proto.EnumName(RpcErrorCode_name, int32(x))
}

func (RpcErrorCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8e4c78ff718d7b27, []int{0}
}

func init() {
	proto.RegisterEnum("mtproto.RpcErrorCode", RpcErrorCode_name, RpcErrorCode_value)
}

func init() { proto.RegisterFile("schema.error.proto", fileDescriptor_8e4c78ff718d7b27) }

var fileDescriptor_8e4c78ff718d7b27 = []byte{
	// 2305 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x9a, 0x6b, 0x90, 0x5c, 0x45,
	0xd9, 0xc7, 0x99, 0xd4, 0x5b, 0xaf, 0x55, 0xa7, 0xac, 0xb2, 0x6b, 0xbc, 0x06, 0x61, 0x51, 0x2e,
	0xca, 0x2d, 0x09, 0x10, 0x82, 0x8a, 0x5a, 0x56, 0xcf, 0xe9, 0x67, 0x66, 0xda, 0x3d, 0xa7, 0xfb,
	0xd0, 0xdd, 0x67, 0x2f, 0xf9, 0xd2, 0x45, 0x62, 0x0c, 0x7e, 0x48, 0x2d, 0x15, 0xc3, 0xf7, 0x94,
	0xa2, 0x09, 0xc8, 0x25, 0x5c, 0x84, 0x44, 0x01, 0x33, 0x93, 0xac, 0xc9, 0x44, 0x3e, 0x64, 0x34,
	0x5a, 0xac, 0xa2, 0xae, 0x1a, 0x75, 0x45, 0xca, 0xc2, 0x7b, 0xc0, 0xa8, 0x9b, 0x88, 0x80, 0x1a,
	0x25, 0xe2, 0xc6, 0x78, 0xd9, 0xaa, 0x58, 0x7d, 0xee, 0xb3, 0x33, 0x93, 0x3e, 0xcb, 0x17, 0x76,
	0xe6, 0x3c, 0xbf, 0xe9, 0xee, 0xa7, 0x9f, 0xcb, 0xbf, 0xfb, 0xc4, 0xa9, 0x7e, 0x7c, 0xe3, 0x6d,
	0x9b, 0xb6, 0xdc, 0xba, 0x7a, 0xd3, 0xd6, 0xad, 0x53, 0x5b, 0x57, 0xdf, 0xbe, 0x75, 0x6a, 0xdb,
	0x54, 0xf5, 0x75, 0x5b, 0xb6, 0x45, 0x7f, 0x5c, 0xb8, 0x6a, 0xf3, 0xc7, 0xb6, 0xdd, 0x76, 0xc7,
	0x86, 0xd5, 0x1b, 0xa7, 0xb6, 0xac, 0xd9, 0x3c, 0xb5, 0x79, 0x6a, 0x4d, 0xf4, 0xf5, 0x86, 0x3b,
	0x3e, 0x1a, 0x7d, 0x8a, 0x3e, 0x44, 0x7f, 0xc5, 0xdc, 0xd5, 0xad, 0x9a, 0xf3, 0x7a, 0x71, 0xfb,
	0x46, 0x30, 0x3f, 0xe5, 0x4e, 0x7d, 0x64, 0x53, 0xf5, 0x8d, 0xce, 0x1b, 0x8a, 0x9f, 0x35, 0x1f,
	0x45, 0x17, 0x54, 0x2f, 0x76, 0xde, 0xd6, 0xf3, 0x65, 0x0d, 0x4b, 0xd0, 0x2c, 0xf4, 0x6b, 0x20,
	0xd0, 0x2e, 0x56, 0x5d, 0xe9, 0xbc, 0xa9, 0xe7, 0x71, 0xc8, 0x46, 0x19, 0x1f, 0x67, 0xe8, 0x01,
	0x56, 0xbd, 0xdc, 0xb9, 0xa4, 0xe7, 0x51, 0xf4, 0x57, 0x7d, 0x6a, 0xeb, 0x96, 0x5b, 0xb7, 0xa5,
	0x56, 0x0f, 0xf6, 0xff, 0x80, 0xa2, 0x3e, 0xf0, 0x50, 0xa1, 0x87, 0x58, 0xf5, 0x62, 0xe7, 0x2d,
	0x3d, 0x8f, 0x24, 0x80, 0xe6, 0xaa, 0x09, 0x02, 0x9d, 0x3e, 0xfb, 0x54, 0xa5, 0x7a, 0xb5, 0x73,
	0xd9, 0xe0, 0xc7, 0xba, 0x4e, 0x3d, 0xd0, 0x3e, 0x6d, 0x08, 0xac, 0x00, 0x1d, 0x3b, 0xf7, 0x54,
	0xa5, 0x7a, 0x8d, 0x73, 0xf9, 0x10, 0xdb, 0xa0, 0xc9, 0x59, 0x6e, 0x3c, 0xbb, 0x63, 0xa6, 0x52,
	0x5d, 0xe5, 0xbc, 0x6b, 0x88, 0x31, 0x03, 0x35, 0xce, 0xc5, 0x68, 0x66, 0x7e, 0xf0, 0xfe, 0x99,
	0xf3, 0xcd, 0x23, 0x94, 0x20, 0x32, 0xdb, 0x5d, 0x8f, 0xce, 0x54, 0xaa, 0x97, 0x39, 0x17, 0x0d,
	0xb1, 0x9d, 0xd0, 0x3e, 0x9e, 0x40, 0x0f, 0x18, 0xa3, 0x4b, 0xfa, 0x5c, 0x4e, 0xb4, 0x80, 0x5b,
	0x42, 0x90, 0x0a, 0x6d, 0x7f, 0x70, 0xa1, 0x52, 0xbd, 0xde, 0xb9, 0x7a, 0x98, 0x81, 0xae, 0x53,
	0x21, 0x15, 0xc3, 0x3e, 0x68, 0xca, 0xc6, 0xb0, 0x47, 0x09, 0x7a, 0xd1, 0x20, 0xd7, 0x39, 0x57,
	0x0d, 0x45, 0x3c, 0xbc, 0x84, 0x98, 0x7b, 0x68, 0xa1, 0x52, 0xbd, 0xd1, 0x59, 0x35, 0x94, 0x88,
	0x9d, 0x16, 0x47, 0x41, 0x46, 0x3d, 0xf9, 0xf0, 0x42, 0xa5, 0xba, 0xce, 0x59, 0x6d, 0xa1, 0x5c,
	0x4e, 0x40, 0x37, 0xb1, 0x6c, 0x6a, 0xf0, 0x03, 0x35, 0x89, 0x76, 0x7d, 0xd6, 0x32, 0xbd, 0x02,
	0x16, 0x13, 0x0b, 0x86, 0xb8, 0xc1, 0xb9, 0xa6, 0x0c, 0x91, 0x4e, 0xee, 0xcc, 0x32, 0x18, 0x98,
	0x08, 0xa8, 0x00, 0x82, 0x8e, 0x3d, 0xb2, 0x50, 0xa9, 0xae, 0x76, 0xde, 0x3d, 0x94, 0xc1, 0x01,
	0xd5, 0x94, 0x64, 0x63, 0x3c, 0xfd, 0x68, 0x29, 0x07, 0x24, 0x6e, 0xe3, 0xae, 0x1b, 0x06, 0x14,
	0x08, 0xda, 0xbb, 0x7b, 0xa1, 0x52, 0x7d, 0x8f, 0x73, 0x5d, 0x39, 0x2c, 0x64, 0x19, 0x78, 0xe7,
	0x9e, 0x85, 0xfe, 0x60, 0x2d, 0x82, 0x26, 0xfe, 0xa4, 0x56, 0x9c, 0xeb, 0x3a, 0x8c, 0xa3, 0x57,
	0xf6, 0x58, 0x96, 0x93, 0x9b, 0xfb, 0xa1, 0xdb, 0x44, 0xcf, 0x7e, 0x6e, 0xa1, 0x52, 0x7d, 0xaf,
	0x73, 0xfd, 0x50, 0x7b, 0x35, 0x19, 0x18, 0x8f, 0x31, 0xa9, 0x44, 0xe8, 0x2a, 0x9e, 0x47, 0xc2,
	0xe1, 0xcf, 0x5b, 0x83, 0xd4, 0x03, 0x1d, 0x60, 0xa1, 0x32, 0xe4, 0xe1, 0xc7, 0x2c, 0xfb, 0x93,
	0x21, 0x32, 0x63, 0xfe, 0x65, 0x98, 0xb5, 0xce, 0xb5, 0x25, 0x86, 0x99, 0xd0, 0x3e, 0x95, 0x92,
	0xb2, 0x06, 0x3a, 0xfe, 0xb8, 0x25, 0xb6, 0x7d, 0xb2, 0x4e, 0xbb, 0x4d, 0x70, 0x47, 0x65, 0xe8,
	0x67, 0x43, 0xcd, 0x3e, 0x61, 0xf1, 0x45, 0xd0, 0xe4, 0x8a, 0xa7, 0xe6, 0x9a, 0x50, 0x1f, 0x98,
	0xa4, 0x9c, 0x49, 0xb4, 0xff, 0x0b, 0xd6, 0x85, 0x81, 0x47, 0x74, 0x4f, 0xfe, 0xed, 0xdc, 0x6b,
	0x49, 0x89, 0x02, 0x13, 0xa7, 0xc4, 0x29, 0x43, 0xac, 0x71, 0xae, 0x1c, 0xbe, 0x2a, 0xd9, 0xd0,
	0xe3, 0x98, 0x2a, 0x5d, 0xc7, 0xd4, 0x03, 0x82, 0x9e, 0x6b, 0x59, 0x7c, 0xd7, 0x13, 0x74, 0x35,
	0xcc, 0x18, 0x10, 0xf4, 0xd3, 0x56, 0xa9, 0x24, 0x4a, 0xa0, 0xba, 0xc7, 0x39, 0x41, 0x3f, 0x6b,
	0x95, 0xaa, 0x25, 0x01, 0x96, 0x72, 0x9c, 0x0b, 0x92, 0x50, 0x3f, 0x6f, 0xd9, 0xfd, 0x5d, 0xa4,
	0x02, 0xc1, 0x15, 0xb8, 0x0a, 0x08, 0xfa, 0x85, 0x6d, 0x61, 0x38, 0x54, 0x4d, 0x3d, 0x0a, 0x93,
	0x3a, 0x00, 0xe1, 0x27, 0xee, 0xfb, 0xa5, 0x81, 0x6e, 0x72, 0xd6, 0xd8, 0x32, 0x3d, 0x08, 0x6b,
	0x1e, 0x95, 0x4d, 0x48, 0xa7, 0xf9, 0x2b, 0xc3, 0x61, 0xe7, 0xe6, 0x72, 0x0e, 0xc1, 0x41, 0xa0,
	0x25, 0x6d, 0xb0, 0x30, 0xd0, 0x75, 0x2e, 0x6a, 0x94, 0x10, 0x60, 0xe8, 0xd7, 0xe6, 0x27, 0xde,
	0xe7, 0xdc, 0x30, 0xf4, 0x27, 0x28, 0x0b, 0x42, 0x35, 0x30, 0xcd, 0x8e, 0xb5, 0x2c, 0x9b, 0x1e,
	0x80, 0x29, 0xcf, 0x79, 0x81, 0x7a, 0xbe, 0x65, 0x29, 0x18, 0x8a, 0x8f, 0x02, 0xcb, 0xcc, 0x5f,
	0xb0, 0x99, 0x33, 0x6e, 0x1c, 0x1f, 0x65, 0x16, 0x67, 0xe8, 0x37, 0xb6, 0xe8, 0x90, 0x8a, 0xba,
	0xa3, 0x20, 0x24, 0xe4, 0x69, 0x7f, 0xdc, 0xc6, 0xb8, 0x9c, 0x29, 0xec, 0xaa, 0xe2, 0x2a, 0x7e,
	0x5b, 0x96, 0x29, 0xe4, 0xc7, 0xef, 0x5a, 0x96, 0xda, 0x67, 0xf2, 0xa3, 0x30, 0xc6, 0xef, 0xad,
	0x63, 0x10, 0xa6, 0x7d, 0x50, 0x4d, 0x9e, 0x33, 0xf3, 0x86, 0x59, 0x2a, 0x06, 0x8a, 0x0c, 0xc1,
	0x2a, 0x9d, 0xcf, 0x09, 0x63, 0x7b, 0xb3, 0xb3, 0xf6, 0x3c, 0x5b, 0x27, 0x24, 0x95, 0x0a, 0x98,
	0x8a, 0x14, 0x91, 0x54, 0xd8, 0x0f, 0x12, 0xf6, 0xa4, 0x61, 0x3f, 0xe0, 0xac, 0x5b, 0x1e, 0x9b,
	0xce, 0xf2, 0x0f, 0xb6, 0xa0, 0xb9, 0x25, 0x04, 0x31, 0x19, 0x75, 0x01, 0xd9, 0xe4, 0x42, 0xa1,
	0x17, 0xad, 0xdb, 0x0a, 0x58, 0xb8, 0xcd, 0x84, 0x8b, 0xa7, 0xf8, 0xc7, 0x96, 0xa5, 0x80, 0x99,
	0x56, 0xd3, 0x53, 0xf2, 0x5e, 0x6a, 0x59, 0x5a, 0x46, 0x46, 0x64, 0xed, 0xef, 0xe5, 0x96, 0xa5,
	0xdd, 0x66, 0x08, 0xe3, 0x4a, 0xfb, 0x9c, 0xd0, 0xba, 0xc1, 0x5e, 0xb1, 0x39, 0xc0, 0x6d, 0x9a,
	0x6a, 0xe7, 0x65, 0x53, 0xfb, 0x53, 0x59, 0x20, 0x10, 0x74, 0xcc, 0x28, 0xbd, 0x3f, 0xdb, 0x4a,
	0x90, 0xdb, 0xc4, 0x4a, 0x63, 0xe2, 0x53, 0x16, 0x7d, 0x15, 0x89, 0x8d, 0xbf, 0xd8, 0x56, 0x93,
	0x26, 0xb3, 0x59, 0x8c, 0x0c, 0x83, 0x80, 0x0b, 0x53, 0xee, 0x4e, 0xd9, 0x30, 0x17, 0x7b, 0x9e,
	0xc6, 0x9e, 0x00, 0x4c, 0x26, 0x35, 0x76, 0x5d, 0x08, 0x0c, 0xf6, 0xd7, 0x65, 0x61, 0x04, 0x5c,
	0x8f, 0x9a, 0x06, 0xf0, 0x37, 0xdb, 0x2e, 0x45, 0x58, 0x3c, 0xd3, 0xc4, 0x7b, 0xaf, 0x1a, 0xe4,
	0xfd, 0xce, 0x8d, 0x16, 0x44, 0x70, 0xc5, 0x5d, 0xee, 0xe9, 0xba, 0x87, 0x1b, 0x79, 0x87, 0x3f,
	0x6d, 0x8b, 0xbd, 0x48, 0x61, 0xc7, 0x9e, 0x4c, 0x99, 0xd7, 0x6c, 0xa9, 0x55, 0xf0, 0x3e, 0x65,
	0x63, 0x54, 0x41, 0xbe, 0x09, 0xff, 0x30, 0xec, 0x07, 0x9d, 0x9b, 0x86, 0x37, 0x5e, 0x01, 0xb2,
	0x19, 0x6d, 0x78, 0x03, 0xe2, 0xdf, 0x90, 0x85, 0x5a, 0xbe, 0x60, 0x8b, 0x14, 0x41, 0x1b, 0x4d,
	0x55, 0x00, 0xce, 0xd8, 0xfc, 0x49, 0xb0, 0xc2, 0xfa, 0xc3, 0x92, 0xe7, 0xcb, 0xfb, 0xb7, 0xad,
	0x55, 0xc5, 0xfd, 0x22, 0x72, 0x0c, 0x01, 0xec, 0xaa, 0x28, 0x26, 0x09, 0xfa, 0x8f, 0xad, 0x98,
	0xfb, 0x40, 0x28, 0xce, 0x86, 0xf9, 0xaf, 0x6d, 0x98, 0x48, 0x5b, 0x09, 0xa8, 0x83, 0x00, 0xe6,
	0xe6, 0x9a, 0x79, 0xd1, 0x70, 0xd7, 0x3a, 0x57, 0x9c, 0xdf, 0xfb, 0xe9, 0x28, 0x9f, 0x68, 0x5b,
	0xea, 0x44, 0x64, 0xad, 0xa8, 0xf2, 0xd2, 0xc2, 0xf9, 0xc9, 0xb6, 0x45, 0x2c, 0xfb, 0x20, 0x25,
	0x36, 0x9b, 0x13, 0xaa, 0x26, 0x17, 0xf9, 0xd6, 0xde, 0xd9, 0xb6, 0x84, 0x52, 0x0a, 0x16, 0xba,
	0xc0, 0xa7, 0xda, 0x96, 0x44, 0xae, 0x85, 0x4a, 0x71, 0x16, 0xef, 0x52, 0x0a, 0x7d, 0xba, 0x24,
	0x14, 0xa9, 0xe7, 0x14, 0xda, 0x61, 0x9b, 0x5d, 0x02, 0x85, 0x22, 0xaf, 0x4b, 0x3b, 0xdb, 0x96,
	0xe0, 0x01, 0xa6, 0xa8, 0xa2, 0x10, 0x4b, 0x7a, 0x8f, 0xb3, 0x06, 0xba, 0xcb, 0x36, 0x37, 0xca,
	0x4c, 0xa2, 0xeb, 0x1a, 0x57, 0xb9, 0xe7, 0xee, 0x6e, 0xdb, 0x14, 0x73, 0xe2, 0xb9, 0x9e, 0x32,
	0xfb, 0x19, 0x1b, 0x25, 0x20, 0xf0, 0x26, 0xb5, 0x8f, 0xc5, 0x68, 0x98, 0x77, 0xa7, 0x7b, 0xda,
	0x96, 0xba, 0x24, 0xdd, 0x26, 0x90, 0xd0, 0x83, 0xb8, 0x99, 0xa6, 0xd8, 0xbd, 0x6d, 0x8b, 0x88,
	0x4a, 0xa7, 0x08, 0x84, 0xc6, 0x4d, 0x31, 0x0b, 0xd8, 0xfb, 0xda, 0x25, 0x4e, 0x45, 0xd1, 0xd2,
	0xea, 0x3c, 0x64, 0x04, 0xdd, 0x6f, 0xf3, 0x7a, 0xd2, 0x0d, 0x0a, 0x07, 0xa9, 0xa3, 0xd3, 0x0b,
	0x95, 0xea, 0x55, 0xce, 0xa5, 0x43, 0x91, 0x31, 0x1a, 0x68, 0x8f, 0xfa, 0x54, 0xa1, 0x1f, 0x4d,
	0xdb, 0x8f, 0x90, 0x8a, 0x6b, 0xec, 0xd5, 0x42, 0xbf, 0x30, 0xa9, 0x67, 0xa6, 0x2d, 0x93, 0x2a,
	0x62, 0xf1, 0x48, 0x3f, 0x9e, 0x2e, 0x75, 0xa2, 0x89, 0x91, 0x80, 0x1a, 0xfd, 0x9f, 0x90, 0xcf,
	0x4e, 0xdb, 0xb4, 0x0b, 0x9e, 0xf4, 0x8d, 0xf8, 0xe0, 0x82, 0xc4, 0x2d, 0x2b, 0xf9, 0x02, 0x08,
	0xba, 0xe7, 0x40, 0x49, 0x56, 0x09, 0x4c, 0x20, 0x12, 0x98, 0x19, 0x7b, 0xef, 0x81, 0xe5, 0x8e,
	0x9b, 0x3b, 0xe8, 0xbe, 0x03, 0xd6, 0xea, 0x97, 0x04, 0x48, 0x54, 0x65, 0x66, 0x3a, 0x96, 0xba,
	0x94, 0x9a, 0x67, 0x99, 0xf5, 0xf5, 0x8e, 0xed, 0x10, 0x1f, 0xbb, 0x90, 0x50, 0xec, 0xf1, 0x46,
	0x21, 0x38, 0xbe, 0xd1, 0xb1, 0x14, 0xda, 0x28, 0xfe, 0xe2, 0x03, 0x98, 0xa6, 0x2c, 0x0d, 0x2f,
	0xf4, 0x74, 0xc7, 0xd2, 0x6b, 0x22, 0x8e, 0x4a, 0x5d, 0xf3, 0xb8, 0x3b, 0x0a, 0x04, 0x7d, 0xb3,
	0x63, 0xc9, 0x7d, 0x60, 0xae, 0x98, 0x0c, 0x14, 0x35, 0x05, 0x2d, 0x6d, 0xf8, 0xdf, 0xea, 0xd8,
	0xb5, 0x4f, 0x8f, 0x38, 0xff, 0x76, 0xc7, 0x92, 0xf6, 0x11, 0x30, 0x2e, 0x4c, 0xdb, 0xcd, 0xfb,
	0xe0, 0x6c, 0xc7, 0x12, 0xbf, 0x49, 0xa3, 0x2e, 0x5c, 0x1b, 0x7d, 0xa7, 0x63, 0x2d, 0x65, 0x39,
	0x92, 0xce, 0xee, 0xbb, 0xcb, 0x81, 0xd2, 0x0a, 0xf1, 0xbd, 0x52, 0x3e, 0x10, 0x20, 0x95, 0xa0,
	0xd1, 0x11, 0xf4, 0x68, 0xc7, 0x92, 0x5a, 0xb1, 0x6a, 0x49, 0xc4, 0x55, 0x80, 0x85, 0xa2, 0x2e,
	0x0d, 0x30, 0x53, 0xe8, 0xfb, 0x1d, 0x9b, 0x58, 0x4a, 0xa4, 0xa6, 0x00, 0x9f, 0x8f, 0x01, 0xe9,
	0x81, 0x7f, 0xd0, 0xb1, 0x57, 0x26, 0xd5, 0x5b, 0xa4, 0x7f, 0xd8, 0xb1, 0x14, 0xbf, 0x20, 0x92,
	0xa8, 0xd9, 0xca, 0xe6, 0x3a, 0x96, 0x36, 0x15, 0x1d, 0xae, 0x7b, 0x4f, 0x91, 0xc7, 0xe6, 0xca,
	0x33, 0xa9, 0xcb, 0x9f, 0x9f, 0xb3, 0xf8, 0xa1, 0xc0, 0xf4, 0x69, 0xdb, 0x17, 0xe6, 0x2c, 0x21,
	0xd8, 0x33, 0xa0, 0x81, 0xa2, 0xd3, 0xeb, 0x5c, 0x99, 0x7b, 0x83, 0x9e, 0xa5, 0x4d, 0xa0, 0xe3,
	0x06, 0x1a, 0x71, 0xde, 0xda, 0x07, 0x85, 0x81, 0xc7, 0x31, 0x41, 0x7b, 0xbb, 0x43, 0xfc, 0x1b,
	0x3f, 0x2f, 0x5c, 0x50, 0xc5, 0x41, 0xdd, 0xea, 0x0e, 0xa9, 0x3b, 0x7d, 0xf6, 0xa9, 0x77, 0xdb,
	0xdd, 0x21, 0x9b, 0xbe, 0x94, 0xc8, 0x45, 0xf5, 0xbe, 0xee, 0x90, 0x1e, 0xd3, 0x37, 0x88, 0xa4,
	0xeb, 0x21, 0x11, 0xbb, 0x04, 0xed, 0x5f, 0x1e, 0x96, 0x8e, 0x36, 0x5d, 0x7a, 0x49, 0xa6, 0x24,
	0xd6, 0x68, 0x03, 0x7d, 0xb1, 0x3b, 0x64, 0xff, 0x8a, 0x84, 0xc7, 0x5d, 0x1c, 0x95, 0xaa, 0x74,
	0x9c, 0x03, 0x65, 0xa6, 0x97, 0xeb, 0xd5, 0x14, 0x3b, 0x68, 0x19, 0x2c, 0xee, 0x82, 0xae, 0xe0,
	0x41, 0xbc, 0x2c, 0xe9, 0x63, 0xcf, 0x43, 0x1d, 0x9b, 0xd7, 0x63, 0x0c, 0x26, 0xf2, 0x8d, 0x3a,
	0xd4, 0x1d, 0x22, 0x8c, 0x7b, 0x06, 0x4a, 0xad, 0xbf, 0xd4, 0xb5, 0x08, 0x9a, 0xa4, 0x58, 0x03,
	0xc9, 0x75, 0x6b, 0x82, 0x1e, 0x69, 0x97, 0x3a, 0x20, 0xe4, 0x57, 0x3e, 0x49, 0x07, 0xdb, 0xbd,
	0xcf, 0x92, 0x73, 0x0a, 0xfc, 0x20, 0xbf, 0x3d, 0x4b, 0xd3, 0xae, 0x16, 0xf5, 0xd7, 0xc5, 0x7d,
	0x96, 0xec, 0xe9, 0x85, 0xe3, 0x68, 0x9f, 0xdf, 0x6f, 0x29, 0x58, 0x1e, 0x66, 0x0d, 0x1d, 0x60,
	0x77, 0x34, 0x5b, 0xdc, 0x63, 0x87, 0x2c, 0x1a, 0xa0, 0x0f, 0x89, 0xbe, 0x71, 0x39, 0x01, 0xf4,
	0xf8, 0x21, 0xdb, 0xbd, 0x49, 0x5e, 0x4c, 0xf5, 0x18, 0x08, 0x69, 0xc2, 0x8b, 0x87, 0x8a, 0x44,
	0xe7, 0xa7, 0xc3, 0x87, 0x4a, 0xf5, 0xdb, 0xbc, 0x13, 0x76, 0x0f, 0xd9, 0xde, 0x1e, 0xd4, 0x78,
	0x58, 0xf0, 0xff, 0x5d, 0x33, 0x16, 0x05, 0x91, 0x09, 0x51, 0x3f, 0x54, 0x21, 0xf6, 0xd2, 0x6b,
	0x2e, 0x74, 0xf7, 0x4c, 0xb9, 0x7b, 0xb7, 0xe2, 0xe4, 0x4e, 0xcf, 0x5a, 0x06, 0xcb, 0xef, 0xea,
	0xa4, 0xae, 0xe3, 0xb1, 0x4c, 0xfc, 0xfd, 0x7d, 0xd6, 0xd2, 0xdb, 0x8a, 0xa0, 0x00, 0xd7, 0xe8,
	0xb1, 0x98, 0x7c, 0xcd, 0x90, 0xef, 0x70, 0x56, 0x2e, 0x79, 0x5d, 0x18, 0x9f, 0xd3, 0xe8, 0x7a,
	0x20, 0x68, 0xd7, 0xfc, 0x80, 0x78, 0x28, 0x5a, 0xe4, 0x01, 0x94, 0xbd, 0x02, 0x78, 0xd9, 0x86,
	0xf4, 0x1d, 0x84, 0xe7, 0x5f, 0x1d, 0x50, 0x90, 0x7a, 0x10, 0x09, 0xd1, 0x85, 0xa6, 0x16, 0x30,
	0xc6, 0x8d, 0x72, 0x9a, 0x3b, 0x5b, 0x96, 0x48, 0xfb, 0xd7, 0xe1, 0x73, 0x03, 0xaa, 0xca, 0xe0,
	0x95, 0x14, 0x6e, 0xa1, 0x77, 0xef, 0x38, 0xd3, 0x9f, 0xb9, 0x83, 0xa9, 0x90, 0x09, 0x68, 0x50,
	0xa9, 0xc0, 0x8c, 0xb6, 0xc7, 0x70, 0x4b, 0xf7, 0x64, 0xe0, 0xfc, 0xb2, 0xfb, 0x72, 0x06, 0x40,
	0x80, 0xa0, 0x7d, 0x86, 0x5c, 0xfa, 0x9a, 0x35, 0x97, 0x65, 0x87, 0x17, 0xcf, 0xf4, 0xab, 0xe6,
	0xec, 0x71, 0x9f, 0xc2, 0xfc, 0xb2, 0x31, 0x5f, 0x5a, 0x82, 0x97, 0x98, 0x47, 0x77, 0x64, 0xee,
	0x64, 0x51, 0x54, 0x7c, 0xa5, 0xc4, 0x28, 0x05, 0xf3, 0x23, 0x25, 0x46, 0x19, 0x90, 0x25, 0x5f,
	0x35, 0xd8, 0x95, 0xce, 0x3b, 0x87, 0x60, 0x84, 0x0a, 0x35, 0xa9, 0x8d, 0x6f, 0x50, 0xd7, 0x58,
	0x2e, 0x3d, 0xae, 0xe5, 0x96, 0xd1, 0x6a, 0x35, 0xf5, 0x71, 0x03, 0xd0, 0xd7, 0x16, 0x07, 0xec,
	0x58, 0x6e, 0x9a, 0x96, 0x66, 0x02, 0x1e, 0xf4, 0xe8, 0xdd, 0x9f, 0x2c, 0x0e, 0xf0, 0x7b, 0x7e,
	0x5a, 0x99, 0x7d, 0xe6, 0x9f, 0x95, 0xea, 0xa5, 0xce, 0xdb, 0xfb, 0x1e, 0xc7, 0x1a, 0x07, 0xd7,
	0x3c, 0x40, 0xf3, 0x2f, 0x9d, 0xad, 0x54, 0xeb, 0xce, 0x87, 0xce, 0x63, 0x93, 0xdc, 0x56, 0x09,
	0x90, 0xa0, 0x92, 0xfb, 0x10, 0x2a, 0xe3, 0xae, 0x99, 0x4f, 0xe5, 0x84, 0xf9, 0x9d, 0x95, 0x4e,
	0xb5, 0x77, 0x09, 0xd1, 0xdb, 0x8d, 0xd9, 0x27, 0xb7, 0xaf, 0xe8, 0x53, 0x37, 0xd1, 0xa3, 0xe8,
	0x55, 0x12, 0x3a, 0x78, 0x64, 0xfb, 0x8a, 0x7e, 0x47, 0x45, 0xcf, 0xa5, 0xc7, 0xc7, 0x7d, 0x4e,
	0x20, 0x7e, 0xe7, 0x34, 0x81, 0x3a, 0xb1, 0xe9, 0x45, 0x22, 0x70, 0x73, 0xd3, 0x26, 0x66, 0x44,
	0x36, 0xf1, 0x28, 0xe8, 0x40, 0xf0, 0x89, 0x49, 0x74, 0x74, 0xf1, 0x5c, 0xfc, 0x9f, 0x29, 0x67,
	0x57, 0x0c, 0x31, 0xcd, 0x57, 0x63, 0x12, 0x01, 0x9d, 0xca, 0x99, 0x8b, 0x9c, 0x37, 0xf7, 0xcc,
	0x84, 0x32, 0x05, 0x82, 0x61, 0x0f, 0xcd, 0x3e, 0xd2, 0x5d, 0xd1, 0x57, 0x89, 0xd3, 0xa7, 0x5a,
	0x04, 0xae, 0x16, 0xa0, 0x42, 0x61, 0xd2, 0x43, 0x60, 0x5f, 0xa2, 0x83, 0x4f, 0x74, 0x57, 0x5c,
	0xf8, 0x7f, 0x3b, 0xf7, 0x8d, 0x5c, 0x50, 0x5b, 0x79, 0xfa, 0xc4, 0x48, 0x65, 0xee, 0xe4, 0x48,
	0xe5, 0xb9, 0x93, 0x23, 0x95, 0xf9, 0x93, 0x23, 0x95, 0xf5, 0xe9, 0xbf, 0xb6, 0xd8, 0xf0, 0xff,
	0xd1, 0xff, 0xd6, 0xfe, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x5b, 0x03, 0x77, 0x3c, 0x93, 0x21, 0x00,
	0x00,
}
